// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/user/v1/user.proto
// Protobuf Java Version: 4.33.6

package com.saltoapis.nebula.user.v1;

@com.google.protobuf.Generated
public interface AppKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.user.v1.AppKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the user's app key. It must have the
   * format of `installations/&#42;&#47;users/&#42;&#47;app-key`. For example:
   * `installations/surelock-homes-hq/users/john-watson/app-key`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Resource name of the user's app key. It must have the
   * format of `installations/&#42;&#47;users/&#42;&#47;app-key`. For example:
   * `installations/surelock-homes-hq/users/john-watson/app-key`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Indicates whether this app key has been assigned or not. This field
   * cannot be modified using a standard
   * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
   * operation. To change the value of this field, you must call
   * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
   * </pre>
   *
   * <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <pre>
   * Indicates whether this app key has been assigned or not. This field
   * cannot be modified using a standard
   * [`UpdateAppKey`][salto.nebula.user.v1.UserService.UpdateAppKey]
   * operation. To change the value of this field, you must call
   * [`AssignAppKey`][salto.nebula.user.v1.UserService.AssignAppKey].
   * </pre>
   *
   * <code>.salto.nebula.user.v1.AppKey.State state = 2;</code>
   * @return The state.
   */
  com.saltoapis.nebula.user.v1.AppKey.State getState();

  /**
   * <pre>
   * Indicates whether this app key has pending updates or not.
   *
   * Deprecated: This field is deprecated and should not be used.
   * </pre>
   *
   * <code>bool outdated = 3;</code>
   * @return The outdated.
   */
  boolean getOutdated();

  /**
   * <pre>
   * Allowed remote operations for the app key.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
   * @return A list containing the remoteOperations.
   */
  java.util.List<com.saltoapis.nebula.type.AppKeyRemoteOperation> getRemoteOperationsList();
  /**
   * <pre>
   * Allowed remote operations for the app key.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
   * @return The count of remoteOperations.
   */
  int getRemoteOperationsCount();
  /**
   * <pre>
   * Allowed remote operations for the app key.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
   * @param index The index of the element to return.
   * @return The remoteOperations at the given index.
   */
  com.saltoapis.nebula.type.AppKeyRemoteOperation getRemoteOperations(int index);
  /**
   * <pre>
   * Allowed remote operations for the app key.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
   * @return A list containing the enum numeric values on the wire for remoteOperations.
   */
  java.util.List<java.lang.Integer>
  getRemoteOperationsValueList();
  /**
   * <pre>
   * Allowed remote operations for the app key.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyRemoteOperation remote_operations = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of remoteOperations at the given index.
   */
  int getRemoteOperationsValue(int index);

  /**
   * <pre>
   * How access to the app key is managed. Determines whether a digital key
   * is created for this app key or not.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.AppKey.Type type = 5;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * How access to the app key is managed. Determines whether a digital key
   * is created for this app key or not.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.AppKey.Type type = 5;</code>
   * @return The type.
   */
  com.saltoapis.nebula.user.v1.AppKey.Type getType();

  /**
   * <pre>
   * The email identity to which the digital key was issued.
   *
   * Set iff `type` is `MANAGED`. At the moment, this is always
   * set for managed app keys, as it is the email used for the digital key
   * binding.
   *
   * This is an assignment-time snapshot and is not subsequently
   * synchronized with `User.email`.
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <pre>
   * The email identity to which the digital key was issued.
   *
   * Set iff `type` is `MANAGED`. At the moment, this is always
   * set for managed app keys, as it is the email used for the digital key
   * binding.
   *
   * This is an assignment-time snapshot and is not subsequently
   * synchronized with `User.email`.
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * The email identity to which the digital key was issued.
   *
   * Set iff `type` is `MANAGED`. At the moment, this is always
   * set for managed app keys, as it is the email used for the digital key
   * binding.
   *
   * This is an assignment-time snapshot and is not subsequently
   * synchronized with `User.email`.
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
