// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/user/v1/user.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.user.v1;

/**
 * <pre>
 * The request message for [`CreateUser`][salto.nebula.user.v1.UserService.CreateUser]
 * </pre>
 *
 * Protobuf type {@code salto.nebula.user.v1.CreateUserRequest}
 */
public  final class CreateUserRequest extends
    com.google.protobuf.GeneratedMessageLite<
        CreateUserRequest, CreateUserRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:salto.nebula.user.v1.CreateUserRequest)
    CreateUserRequestOrBuilder {
  private CreateUserRequest() {
    parent_ = "";
    userId_ = "";
  }
  private int bitField0_;
  public static final int PARENT_FIELD_NUMBER = 1;
  private java.lang.String parent_;
  /**
   * <pre>
   * Resource name of the parent resource where the user is to be created. For
   * example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  @java.lang.Override
  public java.lang.String getParent() {
    return parent_;
  }
  /**
   * <pre>
   * Resource name of the parent resource where the user is to be created. For
   * example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(parent_);
  }
  /**
   * <pre>
   * Resource name of the parent resource where the user is to be created. For
   * example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @param value The parent to set.
   */
  private void setParent(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    parent_ = value;
  }
  /**
   * <pre>
   * Resource name of the parent resource where the user is to be created. For
   * example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  private void clearParent() {

    parent_ = getDefaultInstance().getParent();
  }
  /**
   * <pre>
   * Resource name of the parent resource where the user is to be created. For
   * example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @param value The bytes for parent to set.
   */
  private void setParentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    parent_ = value.toStringUtf8();

  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private java.lang.String userId_;
  /**
   * <pre>
   * The user id to use for this user. In case it's empty the server
   * will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string user_id = 2;</code>
   * @return Whether the userId field is set.
   */
  @java.lang.Override
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The user id to use for this user. In case it's empty the server
   * will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <pre>
   * The user id to use for this user. In case it's empty the server
   * will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <pre>
   * The user id to use for this user. In case it's empty the server
   * will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string user_id = 2;</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    userId_ = value;
  }
  /**
   * <pre>
   * The user id to use for this user. In case it's empty the server
   * will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string user_id = 2;</code>
   */
  private void clearUserId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <pre>
   * The user id to use for this user. In case it's empty the server
   * will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string user_id = 2;</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int USER_FIELD_NUMBER = 3;
  private com.saltoapis.nebula.user.v1.User user_;
  /**
   * <pre>
   * The user resource to be created. Client must not set the `User.name`
   * field.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.User user = 3;</code>
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The user resource to be created. Client must not set the `User.name`
   * field.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.User user = 3;</code>
   */
  @java.lang.Override
  public com.saltoapis.nebula.user.v1.User getUser() {
    return user_ == null ? com.saltoapis.nebula.user.v1.User.getDefaultInstance() : user_;
  }
  /**
   * <pre>
   * The user resource to be created. Client must not set the `User.name`
   * field.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.User user = 3;</code>
   */
  private void setUser(com.saltoapis.nebula.user.v1.User value) {
    value.getClass();
  user_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <pre>
   * The user resource to be created. Client must not set the `User.name`
   * field.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.User user = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUser(com.saltoapis.nebula.user.v1.User value) {
    value.getClass();
  if (user_ != null &&
        user_ != com.saltoapis.nebula.user.v1.User.getDefaultInstance()) {
      user_ =
        com.saltoapis.nebula.user.v1.User.newBuilder(user_).mergeFrom(value).buildPartial();
    } else {
      user_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <pre>
   * The user resource to be created. Client must not set the `User.name`
   * field.
   * </pre>
   *
   * <code>.salto.nebula.user.v1.User user = 3;</code>
   */
  private void clearUser() {  user_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.user.v1.CreateUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.user.v1.CreateUserRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The request message for [`CreateUser`][salto.nebula.user.v1.UserService.CreateUser]
   * </pre>
   *
   * Protobuf type {@code salto.nebula.user.v1.CreateUserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.saltoapis.nebula.user.v1.CreateUserRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.user.v1.CreateUserRequest)
      com.saltoapis.nebula.user.v1.CreateUserRequestOrBuilder {
    // Construct using com.saltoapis.nebula.user.v1.CreateUserRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Resource name of the parent resource where the user is to be created. For
     * example: `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @return The parent.
     */
    @java.lang.Override
    public java.lang.String getParent() {
      return instance.getParent();
    }
    /**
     * <pre>
     * Resource name of the parent resource where the user is to be created. For
     * example: `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @return The bytes for parent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParentBytes() {
      return instance.getParentBytes();
    }
    /**
     * <pre>
     * Resource name of the parent resource where the user is to be created. For
     * example: `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @param value The parent to set.
     * @return This builder for chaining.
     */
    public Builder setParent(
        java.lang.String value) {
      copyOnWrite();
      instance.setParent(value);
      return this;
    }
    /**
     * <pre>
     * Resource name of the parent resource where the user is to be created. For
     * example: `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearParent() {
      copyOnWrite();
      instance.clearParent();
      return this;
    }
    /**
     * <pre>
     * Resource name of the parent resource where the user is to be created. For
     * example: `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @param value The bytes for parent to set.
     * @return This builder for chaining.
     */
    public Builder setParentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setParentBytes(value);
      return this;
    }

    /**
     * <pre>
     * The user id to use for this user. In case it's empty the server
     * will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string user_id = 2;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return instance.hasUserId();
    }
    /**
     * <pre>
     * The user id to use for this user. In case it's empty the server
     * will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <pre>
     * The user id to use for this user. In case it's empty the server
     * will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string user_id = 2;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <pre>
     * The user id to use for this user. In case it's empty the server
     * will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <pre>
     * The user id to use for this user. In case it's empty the server
     * will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <pre>
     * The user id to use for this user. In case it's empty the server
     * will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The user resource to be created. Client must not set the `User.name`
     * field.
     * </pre>
     *
     * <code>.salto.nebula.user.v1.User user = 3;</code>
     */
    @java.lang.Override
    public boolean hasUser() {
      return instance.hasUser();
    }
    /**
     * <pre>
     * The user resource to be created. Client must not set the `User.name`
     * field.
     * </pre>
     *
     * <code>.salto.nebula.user.v1.User user = 3;</code>
     */
    @java.lang.Override
    public com.saltoapis.nebula.user.v1.User getUser() {
      return instance.getUser();
    }
    /**
     * <pre>
     * The user resource to be created. Client must not set the `User.name`
     * field.
     * </pre>
     *
     * <code>.salto.nebula.user.v1.User user = 3;</code>
     */
    public Builder setUser(com.saltoapis.nebula.user.v1.User value) {
      copyOnWrite();
      instance.setUser(value);
      return this;
      }
    /**
     * <pre>
     * The user resource to be created. Client must not set the `User.name`
     * field.
     * </pre>
     *
     * <code>.salto.nebula.user.v1.User user = 3;</code>
     */
    public Builder setUser(
        com.saltoapis.nebula.user.v1.User.Builder builderForValue) {
      copyOnWrite();
      instance.setUser(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The user resource to be created. Client must not set the `User.name`
     * field.
     * </pre>
     *
     * <code>.salto.nebula.user.v1.User user = 3;</code>
     */
    public Builder mergeUser(com.saltoapis.nebula.user.v1.User value) {
      copyOnWrite();
      instance.mergeUser(value);
      return this;
    }
    /**
     * <pre>
     * The user resource to be created. Client must not set the `User.name`
     * field.
     * </pre>
     *
     * <code>.salto.nebula.user.v1.User user = 3;</code>
     */
    public Builder clearUser() {  copyOnWrite();
      instance.clearUser();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.user.v1.CreateUserRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.saltoapis.nebula.user.v1.CreateUserRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "parent_",
            "userId_",
            "user_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u1208" +
              "\u0000\u0003\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.saltoapis.nebula.user.v1.CreateUserRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.saltoapis.nebula.user.v1.CreateUserRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.saltoapis.nebula.user.v1.CreateUserRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:salto.nebula.user.v1.CreateUserRequest)
  private static final com.saltoapis.nebula.user.v1.CreateUserRequest DEFAULT_INSTANCE;
  static {
    CreateUserRequest defaultInstance = new CreateUserRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateUserRequest.class, defaultInstance);
  }

  public static com.saltoapis.nebula.user.v1.CreateUserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateUserRequest> PARSER;

  public static com.google.protobuf.Parser<CreateUserRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

