// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/user/v1/user.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.user.v1;

@com.google.protobuf.Generated
public interface UserAccessRightOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.user.v1.UserAccessRight)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the user's access right association. It
   * must have the format of `installations/&#42;&#47;users/&#42;&#47;access-rights/&#42;`. For
   * example:
   * `installations/surelock-homes-hq/users/john-watson/access-rights/baskerville`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Resource name of the user's access right association. It
   * must have the format of `installations/&#42;&#47;users/&#42;&#47;access-rights/&#42;`. For
   * example:
   * `installations/surelock-homes-hq/users/john-watson/access-rights/baskerville`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The access right resource name to bind as an association to the parent
   * access point. For example:
   * `installations/surelock-homes-hq/access-rights/baskerville`.
   * </pre>
   *
   * <code>string access_right = 2;</code>
   * @return The accessRight.
   */
  java.lang.String getAccessRight();
  /**
   * <pre>
   * The access right resource name to bind as an association to the parent
   * access point. For example:
   * `installations/surelock-homes-hq/access-rights/baskerville`.
   * </pre>
   *
   * <code>string access_right = 2;</code>
   * @return The bytes for accessRight.
   */
  com.google.protobuf.ByteString
      getAccessRightBytes();

  /**
   * <pre>
   * Display name of the associated entity. In this case an access right.
   * </pre>
   *
   * <code>string display_name = 3;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * Display name of the associated entity. In this case an access right.
   * </pre>
   *
   * <code>string display_name = 3;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   * The schedules for the user's access right. If set, this can only be more
   * restrictive than the schedules defined in the associated access right.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule schedules = 4;</code>
   */
  java.util.List<com.saltoapis.nebula.type.Schedule> 
      getSchedulesList();
  /**
   * <pre>
   * The schedules for the user's access right. If set, this can only be more
   * restrictive than the schedules defined in the associated access right.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule schedules = 4;</code>
   */
  com.saltoapis.nebula.type.Schedule getSchedules(int index);
  /**
   * <pre>
   * The schedules for the user's access right. If set, this can only be more
   * restrictive than the schedules defined in the associated access right.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule schedules = 4;</code>
   */
  int getSchedulesCount();
  /**
   * <pre>
   * The schedules for the user's access right. If set, this can only be more
   * restrictive than the schedules defined in the associated access right.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule schedules = 4;</code>
   */
  java.util.List<? extends com.saltoapis.nebula.type.ScheduleOrBuilder> 
      getSchedulesOrBuilderList();
  /**
   * <pre>
   * The schedules for the user's access right. If set, this can only be more
   * restrictive than the schedules defined in the associated access right.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule schedules = 4;</code>
   */
  com.saltoapis.nebula.type.ScheduleOrBuilder getSchedulesOrBuilder(
      int index);

  /**
   * <pre>
   * The computed effective schedules for the user's access right based on the
   * given parent resource.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule effective_schedules = 5;</code>
   */
  java.util.List<com.saltoapis.nebula.type.Schedule> 
      getEffectiveSchedulesList();
  /**
   * <pre>
   * The computed effective schedules for the user's access right based on the
   * given parent resource.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule effective_schedules = 5;</code>
   */
  com.saltoapis.nebula.type.Schedule getEffectiveSchedules(int index);
  /**
   * <pre>
   * The computed effective schedules for the user's access right based on the
   * given parent resource.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule effective_schedules = 5;</code>
   */
  int getEffectiveSchedulesCount();
  /**
   * <pre>
   * The computed effective schedules for the user's access right based on the
   * given parent resource.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule effective_schedules = 5;</code>
   */
  java.util.List<? extends com.saltoapis.nebula.type.ScheduleOrBuilder> 
      getEffectiveSchedulesOrBuilderList();
  /**
   * <pre>
   * The computed effective schedules for the user's access right based on the
   * given parent resource.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.Schedule effective_schedules = 5;</code>
   */
  com.saltoapis.nebula.type.ScheduleOrBuilder getEffectiveSchedulesOrBuilder(
      int index);

  /**
   * <pre>
   * Activation time independent of any time zone or calendar.
   * User access right's association activation time rules:
   * 1. Activation time must be specified in multiples of 10 minutes.
   * Valid examples: 07:40, 12:30, 18:10. Invalid examples: 12:32, 10:15.
   * 2. If no activation time is provided, the current time is used, truncated to the nearest earlier multiple of 10 minutes.
   * For example, if the current time is 14:46, the system will use 14:40.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp activate_time = 6;</code>
   * @return Whether the activateTime field is set.
   */
  boolean hasActivateTime();
  /**
   * <pre>
   * Activation time independent of any time zone or calendar.
   * User access right's association activation time rules:
   * 1. Activation time must be specified in multiples of 10 minutes.
   * Valid examples: 07:40, 12:30, 18:10. Invalid examples: 12:32, 10:15.
   * 2. If no activation time is provided, the current time is used, truncated to the nearest earlier multiple of 10 minutes.
   * For example, if the current time is 14:46, the system will use 14:40.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp activate_time = 6;</code>
   * @return The activateTime.
   */
  com.google.protobuf.Timestamp getActivateTime();
  /**
   * <pre>
   * Activation time independent of any time zone or calendar.
   * User access right's association activation time rules:
   * 1. Activation time must be specified in multiples of 10 minutes.
   * Valid examples: 07:40, 12:30, 18:10. Invalid examples: 12:32, 10:15.
   * 2. If no activation time is provided, the current time is used, truncated to the nearest earlier multiple of 10 minutes.
   * For example, if the current time is 14:46, the system will use 14:40.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp activate_time = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getActivateTimeOrBuilder();

  /**
   * <pre>
   * Expiration time independent of any time zone or calendar.
   * User access right's association expiration time rules:
   * 1. Expiration time must be specified in multiples of 10 minutes.
   * Valid examples: 07:40, 12:30, 18:10. Invalid examples: 12:32, 10:15.
   * 2. When specifying expiration time, it must:
   * - Be at least 10 minutes after activation time.
   * - Always be a multiple of 10 minutes. The system does not round or adjust expiration time for you.
   * For example, if you attempt to set 10:15, the system will reject it.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expire_time = 7;</code>
   * @return Whether the expireTime field is set.
   */
  boolean hasExpireTime();
  /**
   * <pre>
   * Expiration time independent of any time zone or calendar.
   * User access right's association expiration time rules:
   * 1. Expiration time must be specified in multiples of 10 minutes.
   * Valid examples: 07:40, 12:30, 18:10. Invalid examples: 12:32, 10:15.
   * 2. When specifying expiration time, it must:
   * - Be at least 10 minutes after activation time.
   * - Always be a multiple of 10 minutes. The system does not round or adjust expiration time for you.
   * For example, if you attempt to set 10:15, the system will reject it.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expire_time = 7;</code>
   * @return The expireTime.
   */
  com.google.protobuf.Timestamp getExpireTime();
  /**
   * <pre>
   * Expiration time independent of any time zone or calendar.
   * User access right's association expiration time rules:
   * 1. Expiration time must be specified in multiples of 10 minutes.
   * Valid examples: 07:40, 12:30, 18:10. Invalid examples: 12:32, 10:15.
   * 2. When specifying expiration time, it must:
   * - Be at least 10 minutes after activation time.
   * - Always be a multiple of 10 minutes. The system does not round or adjust expiration time for you.
   * For example, if you attempt to set 10:15, the system will reject it.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expire_time = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpireTimeOrBuilder();

  /**
   * <pre>
   * The resource name of the manager resource that owns this user access right. A manager
   * resource is any resource (such as a booking) that creates and governs the
   * lifecycle of this user access right.
   *
   * Example: "installations/surelock-homes-hq/bookings/watson-family-booking"
   *
   * If set, this user access right is considered "managed" and cannot be modified directly.
   * It behaves as a side-effect of the manager resource.
   * </pre>
   *
   * <code>optional string manager = 8;</code>
   * @return Whether the manager field is set.
   */
  boolean hasManager();
  /**
   * <pre>
   * The resource name of the manager resource that owns this user access right. A manager
   * resource is any resource (such as a booking) that creates and governs the
   * lifecycle of this user access right.
   *
   * Example: "installations/surelock-homes-hq/bookings/watson-family-booking"
   *
   * If set, this user access right is considered "managed" and cannot be modified directly.
   * It behaves as a side-effect of the manager resource.
   * </pre>
   *
   * <code>optional string manager = 8;</code>
   * @return The manager.
   */
  java.lang.String getManager();
  /**
   * <pre>
   * The resource name of the manager resource that owns this user access right. A manager
   * resource is any resource (such as a booking) that creates and governs the
   * lifecycle of this user access right.
   *
   * Example: "installations/surelock-homes-hq/bookings/watson-family-booking"
   *
   * If set, this user access right is considered "managed" and cannot be modified directly.
   * It behaves as a side-effect of the manager resource.
   * </pre>
   *
   * <code>optional string manager = 8;</code>
   * @return The bytes for manager.
   */
  com.google.protobuf.ByteString
      getManagerBytes();
}
