// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/intercomadaptor/v1/intercom_adaptor.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.intercomadaptor.v1;

/**
 * <pre>
 * The request message for [CreateIntercomAdaptor][salto.nebula.intercomadaptor.v1.IntercomAdaptorService.CreateIntercomAdaptor]
 * </pre>
 *
 * Protobuf type {@code salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest}
 */
public  final class CreateIntercomAdaptorRequest extends
    com.google.protobuf.GeneratedMessageLite<
        CreateIntercomAdaptorRequest, CreateIntercomAdaptorRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest)
    CreateIntercomAdaptorRequestOrBuilder {
  private CreateIntercomAdaptorRequest() {
    parent_ = "";
    intercomAdaptorId_ = "";
  }
  private int bitField0_;
  public static final int PARENT_FIELD_NUMBER = 1;
  private java.lang.String parent_;
  /**
   * <pre>
   * Resource name of the parent resource where to create the intercom adaptor. For
   * example, `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  @java.lang.Override
  public java.lang.String getParent() {
    return parent_;
  }
  /**
   * <pre>
   * Resource name of the parent resource where to create the intercom adaptor. For
   * example, `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(parent_);
  }
  /**
   * <pre>
   * Resource name of the parent resource where to create the intercom adaptor. For
   * example, `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @param value The parent to set.
   */
  private void setParent(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    parent_ = value;
  }
  /**
   * <pre>
   * Resource name of the parent resource where to create the intercom adaptor. For
   * example, `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  private void clearParent() {

    parent_ = getDefaultInstance().getParent();
  }
  /**
   * <pre>
   * Resource name of the parent resource where to create the intercom adaptor. For
   * example, `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @param value The bytes for parent to set.
   */
  private void setParentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    parent_ = value.toStringUtf8();

  }

  public static final int INTERCOM_ADAPTOR_ID_FIELD_NUMBER = 2;
  private java.lang.String intercomAdaptorId_;
  /**
   * <pre>
   * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
   * server will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string intercom_adaptor_id = 2;</code>
   * @return Whether the intercomAdaptorId field is set.
   */
  @java.lang.Override
  public boolean hasIntercomAdaptorId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
   * server will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string intercom_adaptor_id = 2;</code>
   * @return The intercomAdaptorId.
   */
  @java.lang.Override
  public java.lang.String getIntercomAdaptorId() {
    return intercomAdaptorId_;
  }
  /**
   * <pre>
   * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
   * server will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string intercom_adaptor_id = 2;</code>
   * @return The bytes for intercomAdaptorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIntercomAdaptorIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(intercomAdaptorId_);
  }
  /**
   * <pre>
   * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
   * server will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string intercom_adaptor_id = 2;</code>
   * @param value The intercomAdaptorId to set.
   */
  private void setIntercomAdaptorId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  bitField0_ |= 0x00000001;
    intercomAdaptorId_ = value;
  }
  /**
   * <pre>
   * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
   * server will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string intercom_adaptor_id = 2;</code>
   */
  private void clearIntercomAdaptorId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    intercomAdaptorId_ = getDefaultInstance().getIntercomAdaptorId();
  }
  /**
   * <pre>
   * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
   * server will autogenerate a unique identifier.
   * </pre>
   *
   * <code>optional string intercom_adaptor_id = 2;</code>
   * @param value The bytes for intercomAdaptorId to set.
   */
  private void setIntercomAdaptorIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    intercomAdaptorId_ = value.toStringUtf8();
    bitField0_ |= 0x00000001;
  }

  public static final int INTERCOM_ADAPTOR_FIELD_NUMBER = 3;
  private com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor intercomAdaptor_;
  /**
   * <pre>
   * The intercom adaptor resource to be created. Client must not set the
   * `IntercomAdaptor.name` field.
   * </pre>
   *
   * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
   */
  @java.lang.Override
  public boolean hasIntercomAdaptor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The intercom adaptor resource to be created. Client must not set the
   * `IntercomAdaptor.name` field.
   * </pre>
   *
   * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
   */
  @java.lang.Override
  public com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor getIntercomAdaptor() {
    return intercomAdaptor_ == null ? com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor.getDefaultInstance() : intercomAdaptor_;
  }
  /**
   * <pre>
   * The intercom adaptor resource to be created. Client must not set the
   * `IntercomAdaptor.name` field.
   * </pre>
   *
   * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
   */
  private void setIntercomAdaptor(com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor value) {
    value.getClass();
  intercomAdaptor_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <pre>
   * The intercom adaptor resource to be created. Client must not set the
   * `IntercomAdaptor.name` field.
   * </pre>
   *
   * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeIntercomAdaptor(com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor value) {
    value.getClass();
  if (intercomAdaptor_ != null &&
        intercomAdaptor_ != com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor.getDefaultInstance()) {
      intercomAdaptor_ =
        com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor.newBuilder(intercomAdaptor_).mergeFrom(value).buildPartial();
    } else {
      intercomAdaptor_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <pre>
   * The intercom adaptor resource to be created. Client must not set the
   * `IntercomAdaptor.name` field.
   * </pre>
   *
   * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
   */
  private void clearIntercomAdaptor() {  intercomAdaptor_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The request message for [CreateIntercomAdaptor][salto.nebula.intercomadaptor.v1.IntercomAdaptorService.CreateIntercomAdaptor]
   * </pre>
   *
   * Protobuf type {@code salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest)
      com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequestOrBuilder {
    // Construct using com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @return The parent.
     */
    @java.lang.Override
    public java.lang.String getParent() {
      return instance.getParent();
    }
    /**
     * <pre>
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @return The bytes for parent.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParentBytes() {
      return instance.getParentBytes();
    }
    /**
     * <pre>
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @param value The parent to set.
     * @return This builder for chaining.
     */
    public Builder setParent(
        java.lang.String value) {
      copyOnWrite();
      instance.setParent(value);
      return this;
    }
    /**
     * <pre>
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearParent() {
      copyOnWrite();
      instance.clearParent();
      return this;
    }
    /**
     * <pre>
     * Resource name of the parent resource where to create the intercom adaptor. For
     * example, `installations/surelock-homes-hq`.
     * </pre>
     *
     * <code>string parent = 1;</code>
     * @param value The bytes for parent to set.
     * @return This builder for chaining.
     */
    public Builder setParentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setParentBytes(value);
      return this;
    }

    /**
     * <pre>
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string intercom_adaptor_id = 2;</code>
     * @return Whether the intercomAdaptorId field is set.
     */
    @java.lang.Override
    public boolean hasIntercomAdaptorId() {
      return instance.hasIntercomAdaptorId();
    }
    /**
     * <pre>
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string intercom_adaptor_id = 2;</code>
     * @return The intercomAdaptorId.
     */
    @java.lang.Override
    public java.lang.String getIntercomAdaptorId() {
      return instance.getIntercomAdaptorId();
    }
    /**
     * <pre>
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string intercom_adaptor_id = 2;</code>
     * @return The bytes for intercomAdaptorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIntercomAdaptorIdBytes() {
      return instance.getIntercomAdaptorIdBytes();
    }
    /**
     * <pre>
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string intercom_adaptor_id = 2;</code>
     * @param value The intercomAdaptorId to set.
     * @return This builder for chaining.
     */
    public Builder setIntercomAdaptorId(
        java.lang.String value) {
      copyOnWrite();
      instance.setIntercomAdaptorId(value);
      return this;
    }
    /**
     * <pre>
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string intercom_adaptor_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIntercomAdaptorId() {
      copyOnWrite();
      instance.clearIntercomAdaptorId();
      return this;
    }
    /**
     * <pre>
     * The intercom adaptor ID to use for this intercom adaptor. In case it's empty the
     * server will autogenerate a unique identifier.
     * </pre>
     *
     * <code>optional string intercom_adaptor_id = 2;</code>
     * @param value The bytes for intercomAdaptorId to set.
     * @return This builder for chaining.
     */
    public Builder setIntercomAdaptorIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIntercomAdaptorIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     * </pre>
     *
     * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    @java.lang.Override
    public boolean hasIntercomAdaptor() {
      return instance.hasIntercomAdaptor();
    }
    /**
     * <pre>
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     * </pre>
     *
     * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    @java.lang.Override
    public com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor getIntercomAdaptor() {
      return instance.getIntercomAdaptor();
    }
    /**
     * <pre>
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     * </pre>
     *
     * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    public Builder setIntercomAdaptor(com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor value) {
      copyOnWrite();
      instance.setIntercomAdaptor(value);
      return this;
      }
    /**
     * <pre>
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     * </pre>
     *
     * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    public Builder setIntercomAdaptor(
        com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor.Builder builderForValue) {
      copyOnWrite();
      instance.setIntercomAdaptor(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     * </pre>
     *
     * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    public Builder mergeIntercomAdaptor(com.saltoapis.nebula.intercomadaptor.v1.IntercomAdaptor value) {
      copyOnWrite();
      instance.mergeIntercomAdaptor(value);
      return this;
    }
    /**
     * <pre>
     * The intercom adaptor resource to be created. Client must not set the
     * `IntercomAdaptor.name` field.
     * </pre>
     *
     * <code>.salto.nebula.intercomadaptor.v1.IntercomAdaptor intercom_adaptor = 3;</code>
     */
    public Builder clearIntercomAdaptor() {  copyOnWrite();
      instance.clearIntercomAdaptor();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "parent_",
            "intercomAdaptorId_",
            "intercomAdaptor_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u1208" +
              "\u0000\u0003\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:salto.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest)
  private static final com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest DEFAULT_INSTANCE;
  static {
    CreateIntercomAdaptorRequest defaultInstance = new CreateIntercomAdaptorRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateIntercomAdaptorRequest.class, defaultInstance);
  }

  public static com.saltoapis.nebula.intercomadaptor.v1.CreateIntercomAdaptorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateIntercomAdaptorRequest> PARSER;

  public static com.google.protobuf.Parser<CreateIntercomAdaptorRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

