// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/intercomadaptor/v1/intercom_adaptor.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.intercomadaptor.v1;

public interface ResetIntercomAdaptorMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.intercomadaptor.v1.ResetIntercomAdaptorMetadata)
    com.google.protobuf.MessageLiteOrBuilder {
}
