// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/intercomadaptor/v1/intercom_adaptor.proto

// Protobuf Java Version: 4.26.1
package com.saltoapis.nebula.intercomadaptor.v1;

public interface UnbindIntercomAdaptorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.intercomadaptor.v1.UnbindIntercomAdaptorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource name of the intercom adaptor to be bound. For example:
   * `installations/surelock-homes-hq/intercom-adaptors/baker-street-entrance`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The resource name of the intercom adaptor to be bound. For example:
   * `installations/surelock-homes-hq/intercom-adaptors/baker-street-entrance`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * If set to true, the device identifier is removed (unbound) from the
   * intercom adaptor. Otherwise, the request will only work if the intercom
   * adaptor isn't bound to any previous device identifier.
   * </pre>
   *
   * <code>bool force = 2;</code>
   * @return The force.
   */
  boolean getForce();
}
