// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/digitalkey/v1/digital_key.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.digitalkey.v1;

@com.google.protobuf.Generated
public interface DigitalKeyAccessPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.digitalkey.v1.DigitalKeyAccessPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the access point. It must have the format
   * `digital-keys/{digital-key}/access-points/&#42;`. For example:
   * `digital-keys/baker-street-key/access-points/baker-street-entrance`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Resource name of the access point. It must have the format
   * `digital-keys/{digital-key}/access-points/&#42;`. For example:
   * `digital-keys/baker-street-key/access-points/baker-street-entrance`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Display name of the access point.
   * </pre>
   *
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * Display name of the access point.
   * </pre>
   *
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   * The device which gives coverage to the access point.
   * </pre>
   *
   * <code>string device_id = 3;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   * The device which gives coverage to the access point.
   * </pre>
   *
   * <code>string device_id = 3;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   * Supported technologies used by the app to open an access point.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyTechnology supported_technologies = 4;</code>
   * @return A list containing the supportedTechnologies.
   */
  java.util.List<com.saltoapis.nebula.type.AppKeyTechnology> getSupportedTechnologiesList();
  /**
   * <pre>
   * Supported technologies used by the app to open an access point.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyTechnology supported_technologies = 4;</code>
   * @return The count of supportedTechnologies.
   */
  int getSupportedTechnologiesCount();
  /**
   * <pre>
   * Supported technologies used by the app to open an access point.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyTechnology supported_technologies = 4;</code>
   * @param index The index of the element to return.
   * @return The supportedTechnologies at the given index.
   */
  com.saltoapis.nebula.type.AppKeyTechnology getSupportedTechnologies(int index);
  /**
   * <pre>
   * Supported technologies used by the app to open an access point.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyTechnology supported_technologies = 4;</code>
   * @return A list containing the enum numeric values on the wire for supportedTechnologies.
   */
  java.util.List<java.lang.Integer>
  getSupportedTechnologiesValueList();
  /**
   * <pre>
   * Supported technologies used by the app to open an access point.
   * </pre>
   *
   * <code>repeated .salto.nebula.type.AppKeyTechnology supported_technologies = 4;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of supportedTechnologies at the given index.
   */
  int getSupportedTechnologiesValue(int index);
}
