// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/digitalkey/v1/digital_key.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.digitalkey.v1;

public interface DigitalKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.digitalkey.v1.DigitalKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the digital key. It must have the format of
   * `digital-keys/&#42;`. For example: `digital-keys/baker-street-entrance`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Resource name of the digital key. It must have the format of
   * `digital-keys/&#42;`. For example: `digital-keys/baker-street-entrance`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * An app key.
   * </pre>
   *
   * <code>.salto.nebula.digitalkey.v1.DigitalKey.AppKey app_key = 2;</code>
   * @return Whether the appKey field is set.
   */
  boolean hasAppKey();
  /**
   * <pre>
   * An app key.
   * </pre>
   *
   * <code>.salto.nebula.digitalkey.v1.DigitalKey.AppKey app_key = 2;</code>
   * @return The appKey.
   */
  com.saltoapis.nebula.digitalkey.v1.DigitalKey.AppKey getAppKey();
  /**
   * <pre>
   * An app key.
   * </pre>
   *
   * <code>.salto.nebula.digitalkey.v1.DigitalKey.AppKey app_key = 2;</code>
   */
  com.saltoapis.nebula.digitalkey.v1.DigitalKey.AppKeyOrBuilder getAppKeyOrBuilder();

  /**
   * <pre>
   * A wallet key.
   * </pre>
   *
   * <code>.salto.nebula.digitalkey.v1.DigitalKey.WalletKey wallet_key = 3;</code>
   * @return Whether the walletKey field is set.
   */
  boolean hasWalletKey();
  /**
   * <pre>
   * A wallet key.
   * </pre>
   *
   * <code>.salto.nebula.digitalkey.v1.DigitalKey.WalletKey wallet_key = 3;</code>
   * @return The walletKey.
   */
  com.saltoapis.nebula.digitalkey.v1.DigitalKey.WalletKey getWalletKey();
  /**
   * <pre>
   * A wallet key.
   * </pre>
   *
   * <code>.salto.nebula.digitalkey.v1.DigitalKey.WalletKey wallet_key = 3;</code>
   */
  com.saltoapis.nebula.digitalkey.v1.DigitalKey.WalletKeyOrBuilder getWalletKeyOrBuilder();

  com.saltoapis.nebula.digitalkey.v1.DigitalKey.TypeCase getTypeCase();
}
