// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/gateway/v1/gateway.proto

// Protobuf Java Version: 4.26.1
package com.saltoapis.nebula.gateway.v1;

public interface BindGatewayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.gateway.v1.BindGatewayResponse)
    com.google.protobuf.MessageOrBuilder {
}
