// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/gateway/v1/gateway.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.gateway.v1;

public interface ResetGatewayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.gateway.v1.ResetGatewayResponse)
    com.google.protobuf.MessageOrBuilder {
}
