// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/gateway/v1/gateway.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.gateway.v1;

/**
 * <pre>
 * The request message for [UpdateGateway][salto.nebula.gateway.v1.GatewayService.UpdateGateway]
 * </pre>
 *
 * Protobuf type {@code salto.nebula.gateway.v1.UpdateGatewayRequest}
 */
public  final class UpdateGatewayRequest extends
    com.google.protobuf.GeneratedMessageLite<
        UpdateGatewayRequest, UpdateGatewayRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:salto.nebula.gateway.v1.UpdateGatewayRequest)
    UpdateGatewayRequestOrBuilder {
  private UpdateGatewayRequest() {
  }
  private int bitField0_;
  public static final int GATEWAY_FIELD_NUMBER = 1;
  private com.saltoapis.nebula.gateway.v1.Gateway gateway_;
  /**
   * <pre>
   * The gateway resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
   */
  @java.lang.Override
  public boolean hasGateway() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The gateway resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
   */
  @java.lang.Override
  public com.saltoapis.nebula.gateway.v1.Gateway getGateway() {
    return gateway_ == null ? com.saltoapis.nebula.gateway.v1.Gateway.getDefaultInstance() : gateway_;
  }
  /**
   * <pre>
   * The gateway resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
   */
  private void setGateway(com.saltoapis.nebula.gateway.v1.Gateway value) {
    value.getClass();
  gateway_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <pre>
   * The gateway resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeGateway(com.saltoapis.nebula.gateway.v1.Gateway value) {
    value.getClass();
  if (gateway_ != null &&
        gateway_ != com.saltoapis.nebula.gateway.v1.Gateway.getDefaultInstance()) {
      gateway_ =
        com.saltoapis.nebula.gateway.v1.Gateway.newBuilder(gateway_).mergeFrom(value).buildPartial();
    } else {
      gateway_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * The gateway resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
   */
  private void clearGateway() {  gateway_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int UPDATE_MASK_FIELD_NUMBER = 2;
  private com.google.protobuf.FieldMask updateMask_;
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  @java.lang.Override
  public boolean hasUpdateMask() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldMask getUpdateMask() {
    return updateMask_ == null ? com.google.protobuf.FieldMask.getDefaultInstance() : updateMask_;
  }
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  private void setUpdateMask(com.google.protobuf.FieldMask value) {
    value.getClass();
  updateMask_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeUpdateMask(com.google.protobuf.FieldMask value) {
    value.getClass();
  if (updateMask_ != null &&
        updateMask_ != com.google.protobuf.FieldMask.getDefaultInstance()) {
      updateMask_ =
        com.google.protobuf.FieldMask.newBuilder(updateMask_).mergeFrom(value).buildPartial();
    } else {
      updateMask_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  private void clearUpdateMask() {  updateMask_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The request message for [UpdateGateway][salto.nebula.gateway.v1.GatewayService.UpdateGateway]
   * </pre>
   *
   * Protobuf type {@code salto.nebula.gateway.v1.UpdateGatewayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.gateway.v1.UpdateGatewayRequest)
      com.saltoapis.nebula.gateway.v1.UpdateGatewayRequestOrBuilder {
    // Construct using com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The gateway resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
     */
    @java.lang.Override
    public boolean hasGateway() {
      return instance.hasGateway();
    }
    /**
     * <pre>
     * The gateway resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
     */
    @java.lang.Override
    public com.saltoapis.nebula.gateway.v1.Gateway getGateway() {
      return instance.getGateway();
    }
    /**
     * <pre>
     * The gateway resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
     */
    public Builder setGateway(com.saltoapis.nebula.gateway.v1.Gateway value) {
      copyOnWrite();
      instance.setGateway(value);
      return this;
      }
    /**
     * <pre>
     * The gateway resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
     */
    public Builder setGateway(
        com.saltoapis.nebula.gateway.v1.Gateway.Builder builderForValue) {
      copyOnWrite();
      instance.setGateway(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The gateway resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
     */
    public Builder mergeGateway(com.saltoapis.nebula.gateway.v1.Gateway value) {
      copyOnWrite();
      instance.mergeGateway(value);
      return this;
    }
    /**
     * <pre>
     * The gateway resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.gateway.v1.Gateway gateway = 1;</code>
     */
    public Builder clearGateway() {  copyOnWrite();
      instance.clearGateway();
      return this;
    }

    /**
     * <pre>
     * The update mask applied to the resource.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    @java.lang.Override
    public boolean hasUpdateMask() {
      return instance.hasUpdateMask();
    }
    /**
     * <pre>
     * The update mask applied to the resource.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.FieldMask getUpdateMask() {
      return instance.getUpdateMask();
    }
    /**
     * <pre>
     * The update mask applied to the resource.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder setUpdateMask(com.google.protobuf.FieldMask value) {
      copyOnWrite();
      instance.setUpdateMask(value);
      return this;
      }
    /**
     * <pre>
     * The update mask applied to the resource.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder setUpdateMask(
        com.google.protobuf.FieldMask.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdateMask(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The update mask applied to the resource.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder mergeUpdateMask(com.google.protobuf.FieldMask value) {
      copyOnWrite();
      instance.mergeUpdateMask(value);
      return this;
    }
    /**
     * <pre>
     * The update mask applied to the resource.
     * </pre>
     *
     * <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    public Builder clearUpdateMask() {  copyOnWrite();
      instance.clearUpdateMask();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.gateway.v1.UpdateGatewayRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "gateway_",
            "updateMask_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:salto.nebula.gateway.v1.UpdateGatewayRequest)
  private static final com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest DEFAULT_INSTANCE;
  static {
    UpdateGatewayRequest defaultInstance = new UpdateGatewayRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UpdateGatewayRequest.class, defaultInstance);
  }

  public static com.saltoapis.nebula.gateway.v1.UpdateGatewayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UpdateGatewayRequest> PARSER;

  public static com.google.protobuf.Parser<UpdateGatewayRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

