// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/event/v1/types.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.event.v1;

public interface AccessPointUpdatedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.event.v1.AccessPointUpdated)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Access point updated.
   * </pre>
   *
   * <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 1;</code>
   * @return Whether the accessPoint field is set.
   */
  boolean hasAccessPoint();
  /**
   * <pre>
   * Access point updated.
   * </pre>
   *
   * <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 1;</code>
   * @return The accessPoint.
   */
  com.saltoapis.nebula.accesspoint.v1.AccessPoint getAccessPoint();
  /**
   * <pre>
   * Access point updated.
   * </pre>
   *
   * <code>.salto.nebula.accesspoint.v1.AccessPoint access_point = 1;</code>
   */
  com.saltoapis.nebula.accesspoint.v1.AccessPointOrBuilder getAccessPointOrBuilder();

  /**
   * <pre>
   * The actor who updated the access point.
   * </pre>
   *
   * <code>.salto.nebula.event.v1.Principal actor = 2;</code>
   * @return Whether the actor field is set.
   */
  boolean hasActor();
  /**
   * <pre>
   * The actor who updated the access point.
   * </pre>
   *
   * <code>.salto.nebula.event.v1.Principal actor = 2;</code>
   * @return The actor.
   */
  com.saltoapis.nebula.event.v1.Principal getActor();
  /**
   * <pre>
   * The actor who updated the access point.
   * </pre>
   *
   * <code>.salto.nebula.event.v1.Principal actor = 2;</code>
   */
  com.saltoapis.nebula.event.v1.PrincipalOrBuilder getActorOrBuilder();
}
