// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/event/v1/types.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.event.v1;

@com.google.protobuf.Generated
public interface AccessRightDeletedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.event.v1.AccessRightDeleted)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Access right deleted.
   * </pre>
   *
   * <code>.salto.nebula.accessright.v1.AccessRight access_right = 1;</code>
   * @return Whether the accessRight field is set.
   */
  boolean hasAccessRight();
  /**
   * <pre>
   * Access right deleted.
   * </pre>
   *
   * <code>.salto.nebula.accessright.v1.AccessRight access_right = 1;</code>
   * @return The accessRight.
   */
  com.saltoapis.nebula.accessright.v1.AccessRight getAccessRight();
  /**
   * <pre>
   * Access right deleted.
   * </pre>
   *
   * <code>.salto.nebula.accessright.v1.AccessRight access_right = 1;</code>
   */
  com.saltoapis.nebula.accessright.v1.AccessRightOrBuilder getAccessRightOrBuilder();

  /**
   * <pre>
   * The actor who deleted the access right.
   * </pre>
   *
   * <code>.salto.nebula.event.v1.Principal actor = 2;</code>
   * @return Whether the actor field is set.
   */
  boolean hasActor();
  /**
   * <pre>
   * The actor who deleted the access right.
   * </pre>
   *
   * <code>.salto.nebula.event.v1.Principal actor = 2;</code>
   * @return The actor.
   */
  com.saltoapis.nebula.event.v1.Principal getActor();
  /**
   * <pre>
   * The actor who deleted the access right.
   * </pre>
   *
   * <code>.salto.nebula.event.v1.Principal actor = 2;</code>
   */
  com.saltoapis.nebula.event.v1.PrincipalOrBuilder getActorOrBuilder();
}
