// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/event/v1/types.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.event.v1;

/**
 * <pre>
 * A reusable container that holds the previous values of any fields that were
 * changed during an update operation. This message is designed to be generic
 * and can be included in any resource update event (for example,
 * `AccessPointUpdated`, `UserUpdated`, …) to provide a clear and explicit
 * diff of what was modified.
 * </pre>
 *
 * Protobuf type {@code salto.nebula.event.v1.PreviousValues}
 */
public final class PreviousValues extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:salto.nebula.event.v1.PreviousValues)
    PreviousValuesOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      PreviousValues.class.getName());
  }
  // Use PreviousValues.newBuilder() to construct.
  private PreviousValues(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PreviousValues() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.saltoapis.nebula.event.v1.TypesProto.internal_static_salto_nebula_event_v1_PreviousValues_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetValues();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.saltoapis.nebula.event.v1.TypesProto.internal_static_salto_nebula_event_v1_PreviousValues_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.saltoapis.nebula.event.v1.PreviousValues.class, com.saltoapis.nebula.event.v1.PreviousValues.Builder.class);
  }

  public static final int VALUES_FIELD_NUMBER = 1;
  private static final class ValuesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.Value> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                com.saltoapis.nebula.event.v1.TypesProto.internal_static_salto_nebula_event_v1_PreviousValues_ValuesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                com.google.protobuf.Value.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.Value> values_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
  internalGetValues() {
    if (values_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ValuesDefaultEntryHolder.defaultEntry);
    }
    return values_;
  }
  public int getValuesCount() {
    return internalGetValues().getMap().size();
  }
  /**
   * <pre>
   * A map where the key is the field name of the changed attribute (for
   * example, "display_name") and the value is the field's value before the
   * update was applied. Only fields that were actually changed will be present
   * in this map.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
   */
  @java.lang.Override
  public boolean containsValues(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetValues().getMap().containsKey(key);
  }
  /**
   * Use {@link #getValuesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.Value> getValues() {
    return getValuesMap();
  }
  /**
   * <pre>
   * A map where the key is the field name of the changed attribute (for
   * example, "display_name") and the value is the field's value before the
   * update was applied. Only fields that were actually changed will be present
   * in this map.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.google.protobuf.Value> getValuesMap() {
    return internalGetValues().getMap();
  }
  /**
   * <pre>
   * A map where the key is the field name of the changed attribute (for
   * example, "display_name") and the value is the field's value before the
   * update was applied. Only fields that were actually changed will be present
   * in this map.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
com.google.protobuf.Value getValuesOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.Value defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.Value> map =
        internalGetValues().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * A map where the key is the field name of the changed attribute (for
   * example, "display_name") and the value is the field's value before the
   * update was applied. Only fields that were actually changed will be present
   * in this map.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Value getValuesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.Value> map =
        internalGetValues().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetValues(),
        ValuesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
         : internalGetValues().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
      values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, values__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.saltoapis.nebula.event.v1.PreviousValues)) {
      return super.equals(obj);
    }
    com.saltoapis.nebula.event.v1.PreviousValues other = (com.saltoapis.nebula.event.v1.PreviousValues) obj;

    if (!internalGetValues().equals(
        other.internalGetValues())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetValues().getMap().isEmpty()) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetValues().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.event.v1.PreviousValues parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.saltoapis.nebula.event.v1.PreviousValues parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saltoapis.nebula.event.v1.PreviousValues parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.event.v1.PreviousValues prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A reusable container that holds the previous values of any fields that were
   * changed during an update operation. This message is designed to be generic
   * and can be included in any resource update event (for example,
   * `AccessPointUpdated`, `UserUpdated`, …) to provide a clear and explicit
   * diff of what was modified.
   * </pre>
   *
   * Protobuf type {@code salto.nebula.event.v1.PreviousValues}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.event.v1.PreviousValues)
      com.saltoapis.nebula.event.v1.PreviousValuesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.saltoapis.nebula.event.v1.TypesProto.internal_static_salto_nebula_event_v1_PreviousValues_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.saltoapis.nebula.event.v1.TypesProto.internal_static_salto_nebula_event_v1_PreviousValues_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.saltoapis.nebula.event.v1.PreviousValues.class, com.saltoapis.nebula.event.v1.PreviousValues.Builder.class);
    }

    // Construct using com.saltoapis.nebula.event.v1.PreviousValues.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableValues().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.saltoapis.nebula.event.v1.TypesProto.internal_static_salto_nebula_event_v1_PreviousValues_descriptor;
    }

    @java.lang.Override
    public com.saltoapis.nebula.event.v1.PreviousValues getDefaultInstanceForType() {
      return com.saltoapis.nebula.event.v1.PreviousValues.getDefaultInstance();
    }

    @java.lang.Override
    public com.saltoapis.nebula.event.v1.PreviousValues build() {
      com.saltoapis.nebula.event.v1.PreviousValues result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.saltoapis.nebula.event.v1.PreviousValues buildPartial() {
      com.saltoapis.nebula.event.v1.PreviousValues result = new com.saltoapis.nebula.event.v1.PreviousValues(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.saltoapis.nebula.event.v1.PreviousValues result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.values_ = internalGetValues().build(ValuesDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.saltoapis.nebula.event.v1.PreviousValues) {
        return mergeFrom((com.saltoapis.nebula.event.v1.PreviousValues)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.saltoapis.nebula.event.v1.PreviousValues other) {
      if (other == com.saltoapis.nebula.event.v1.PreviousValues.getDefaultInstance()) return this;
      internalGetMutableValues().mergeFrom(
          other.internalGetValues());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableValues().ensureBuilderMap().put(
                  values__.getKey(), values__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ValuesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value> {
      @java.lang.Override
      public com.google.protobuf.Value build(com.google.protobuf.ValueOrBuilder val) {
        if (val instanceof com.google.protobuf.Value) { return (com.google.protobuf.Value) val; }
        return ((com.google.protobuf.Value.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value> defaultEntry() {
        return ValuesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ValuesConverter valuesConverter = new ValuesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder> values_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder>
        internalGetValues() {
      if (values_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(valuesConverter);
      }
      return values_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, com.google.protobuf.ValueOrBuilder, com.google.protobuf.Value, com.google.protobuf.Value.Builder>
        internalGetMutableValues() {
      if (values_ == null) {
        values_ = new com.google.protobuf.MapFieldBuilder<>(valuesConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return values_;
    }
    public int getValuesCount() {
      return internalGetValues().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    @java.lang.Override
    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetValues().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getValues() {
      return getValuesMap();
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getValuesMap() {
      return internalGetValues().getImmutableMap();
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.Value getValuesOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> map = internalGetMutableValues().ensureBuilderMap();
      return map.containsKey(key) ? valuesConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> map = internalGetMutableValues().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return valuesConverter.build(map.get(key));
    }
    public Builder clearValues() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableValues().clear();
      return this;
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    public Builder removeValues(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableValues().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value>
        getMutableValues() {
      bitField0_ |= 0x00000001;
      return internalGetMutableValues().ensureMessageMap();
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    public Builder putValues(
        java.lang.String key,
        com.google.protobuf.Value value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableValues().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    public Builder putAllValues(
        java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableValues().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * A map where the key is the field name of the changed attribute (for
     * example, "display_name") and the value is the field's value before the
     * update was applied. Only fields that were actually changed will be present
     * in this map.
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Value&gt; values = 1;</code>
     */
    public com.google.protobuf.Value.Builder putValuesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, com.google.protobuf.ValueOrBuilder> builderMap = internalGetMutableValues().ensureBuilderMap();
      com.google.protobuf.ValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = com.google.protobuf.Value.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof com.google.protobuf.Value) {
        entry = ((com.google.protobuf.Value) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (com.google.protobuf.Value.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.event.v1.PreviousValues)
  }

  // @@protoc_insertion_point(class_scope:salto.nebula.event.v1.PreviousValues)
  private static final com.saltoapis.nebula.event.v1.PreviousValues DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.saltoapis.nebula.event.v1.PreviousValues();
  }

  public static com.saltoapis.nebula.event.v1.PreviousValues getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreviousValues>
      PARSER = new com.google.protobuf.AbstractParser<PreviousValues>() {
    @java.lang.Override
    public PreviousValues parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PreviousValues> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreviousValues> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.saltoapis.nebula.event.v1.PreviousValues getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

