// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/event/v1/types.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.event.v1;

public final class TypesProto {
  private TypesProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      TypesProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_Principal_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_Principal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_PreviousValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_PreviousValues_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_PreviousValues_ValuesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_PreviousValues_ValuesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointUnlocked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointUnlocked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointLocked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointLocked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointForcedOpen_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointForcedOpen_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointClosed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointClosed_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessDenied_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessDenied_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessPointLeftOpen_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessPointLeftOpen_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightAccessPointCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightAccessPointCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightAccessPointDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightAccessPointDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserBlocked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserBlocked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserUnblocked_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserUnblocked_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserAccessRightCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserAccessRightCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserAccessRightUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserAccessRightUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UserAccessRightDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UserAccessRightDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_CardKeyAssigned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_CardKeyAssigned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_CardKeyCanceled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_CardKeyCanceled_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AppKeyAssigned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AppKeyAssigned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AppKeyCanceled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AppKeyCanceled_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_WalletKeyAssigned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_WalletKeyAssigned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_WalletKeyCanceled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_WalletKeyCanceled_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UnitMovedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UnitMovedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UnitMovedOut_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UnitMovedOut_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UnitCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UnitCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UnitUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UnitUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_UnitDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_UnitDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_EmergencyKeyCreated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_EmergencyKeyCreated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_EmergencyKeyUpdated_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_EmergencyKeyUpdated_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_EmergencyKeyDeleted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_EmergencyKeyDeleted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_ElectronicKeyAssigned_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_ElectronicKeyAssigned_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_ElectronicKeyCanceled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_ElectronicKeyCanceled_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_salto_nebula_event_v1_AccessGranted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_salto_nebula_event_v1_AccessGranted_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!salto/nebula/event/v1/types.proto\022\025sal" +
      "to.nebula.event.v1\032\034google/protobuf/stru" +
      "ct.proto\032.salto/nebula/accesspoint/v1/ac" +
      "cess_point.proto\032.salto/nebula/accessrig" +
      "ht/v1/access_right.proto\032+salto/nebula/c" +
      "ontroller/v1/controller.proto\0320salto/neb" +
      "ula/emergencykey/v1/emergency_key.proto\032" +
      "\037salto/nebula/unit/v1/unit.proto\032\037salto/" +
      "nebula/user/v1/user.proto\"?\n\tPrincipal\022*" +
      "\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1.User" +
      "H\000B\006\n\004type\"\226\001\n\016PreviousValues\022A\n\006values\030" +
      "\001 \003(\01321.salto.nebula.event.v1.PreviousVa" +
      "lues.ValuesEntry\032A\n\013ValuesEntry\022\013\n\003key\030\001" +
      " \001(\t\022%\n\005value\030\002 \001(\0132\026.google.protobuf.Va" +
      "lue\"\205\001\n\022AccessPointCreated\022>\n\014access_poi" +
      "nt\030\001 \001(\0132(.salto.nebula.accesspoint.v1.A" +
      "ccessPoint\022/\n\005actor\030\002 \001(\0132 .salto.nebula" +
      ".event.v1.Principal\"\305\001\n\022AccessPointUpdat" +
      "ed\022>\n\014access_point\030\001 \001(\0132(.salto.nebula." +
      "accesspoint.v1.AccessPoint\022/\n\005actor\030\002 \001(" +
      "\0132 .salto.nebula.event.v1.Principal\022>\n\017p" +
      "revious_values\030\003 \001(\0132%.salto.nebula.even" +
      "t.v1.PreviousValues\"\205\001\n\022AccessPointDelet" +
      "ed\022>\n\014access_point\030\001 \001(\0132(.salto.nebula." +
      "accesspoint.v1.AccessPoint\022/\n\005actor\030\002 \001(" +
      "\0132 .salto.nebula.event.v1.Principal\"\247\004\n\023" +
      "AccessPointUnlocked\022>\n\014access_point\030\001 \001(" +
      "\0132(.salto.nebula.accesspoint.v1.AccessPo" +
      "int\022(\n\004user\030\002 \001(\0132\032.salto.nebula.user.v1" +
      ".User\022C\n\remergency_key\030\003 \001(\0132*.salto.neb" +
      "ula.emergencykey.v1.EmergencyKeyH\000\0221\n\010ca" +
      "rd_key\030\004 \001(\0132\035.salto.nebula.user.v1.Card" +
      "KeyH\000\022/\n\007app_key\030\005 \001(\0132\034.salto.nebula.us" +
      "er.v1.AppKeyH\000\0225\n\nwallet_key\030\006 \001(\0132\037.sal" +
      "to.nebula.user.v1.WalletKeyH\000\0222\n\010passcod" +
      "e\030\007 \001(\0132\036.salto.nebula.user.v1.PasscodeH" +
      "\000\022G\n\tdirection\030\010 \001(\01624.salto.nebula.even" +
      "t.v1.AccessPointUnlocked.Direction\";\n\tDi" +
      "rection\022\031\n\025DIRECTION_UNSPECIFIED\020\000\022\t\n\005EN" +
      "TRY\020\001\022\010\n\004EXIT\020\002B\014\n\ncredential\"\237\003\n\021Access" +
      "PointLocked\022>\n\014access_point\030\001 \001(\0132(.salt" +
      "o.nebula.accesspoint.v1.AccessPoint\022(\n\004u" +
      "ser\030\002 \001(\0132\032.salto.nebula.user.v1.User\022C\n" +
      "\remergency_key\030\003 \001(\0132*.salto.nebula.emer" +
      "gencykey.v1.EmergencyKeyH\000\0221\n\010card_key\030\004" +
      " \001(\0132\035.salto.nebula.user.v1.CardKeyH\000\022/\n" +
      "\007app_key\030\005 \001(\0132\034.salto.nebula.user.v1.Ap" +
      "pKeyH\000\0225\n\nwallet_key\030\006 \001(\0132\037.salto.nebul" +
      "a.user.v1.WalletKeyH\000\0222\n\010passcode\030\007 \001(\0132" +
      "\036.salto.nebula.user.v1.PasscodeH\000B\014\n\ncre" +
      "dential\"W\n\025AccessPointForcedOpen\022>\n\014acce" +
      "ss_point\030\001 \001(\0132(.salto.nebula.accesspoin" +
      "t.v1.AccessPoint\"S\n\021AccessPointClosed\022>\n" +
      "\014access_point\030\001 \001(\0132(.salto.nebula.acces" +
      "spoint.v1.AccessPoint\"\254\004\n\014AccessDenied\022>" +
      "\n\014access_point\030\001 \001(\0132(.salto.nebula.acce" +
      "sspoint.v1.AccessPoint\022(\n\004user\030\002 \001(\0132\032.s" +
      "alto.nebula.user.v1.User\022:\n\006reason\030\003 \001(\016" +
      "2*.salto.nebula.event.v1.AccessDenied.Re" +
      "ason\022C\n\remergency_key\030\004 \001(\0132*.salto.nebu" +
      "la.emergencykey.v1.EmergencyKeyH\000\0221\n\010car" +
      "d_key\030\005 \001(\0132\035.salto.nebula.user.v1.CardK" +
      "eyH\000\022/\n\007app_key\030\006 \001(\0132\034.salto.nebula.use" +
      "r.v1.AppKeyH\000\0225\n\nwallet_key\030\007 \001(\0132\037.salt" +
      "o.nebula.user.v1.WalletKeyH\000\0222\n\010passcode" +
      "\030\010 \001(\0132\036.salto.nebula.user.v1.PasscodeH\000" +
      "\"T\n\006Reason\022\026\n\022REASON_UNSPECIFIED\020\000\022\026\n\022CR" +
      "EDENTIAL_EXPIRED\020\001\022\032\n\026CREDENTIAL_UNACTIV" +
      "ATED\020\002B\014\n\ncredential\"U\n\023AccessPointLeftO" +
      "pen\022>\n\014access_point\030\001 \001(\0132(.salto.nebula" +
      ".accesspoint.v1.AccessPoint\"\205\001\n\022AccessRi" +
      "ghtCreated\022>\n\014access_right\030\001 \001(\0132(.salto" +
      ".nebula.accessright.v1.AccessRight\022/\n\005ac" +
      "tor\030\002 \001(\0132 .salto.nebula.event.v1.Princi" +
      "pal\"\305\001\n\022AccessRightUpdated\022>\n\014access_rig" +
      "ht\030\001 \001(\0132(.salto.nebula.accessright.v1.A" +
      "ccessRight\022/\n\005actor\030\002 \001(\0132 .salto.nebula" +
      ".event.v1.Principal\022>\n\017previous_values\030\003" +
      " \001(\0132%.salto.nebula.event.v1.PreviousVal" +
      "ues\"\205\001\n\022AccessRightDeleted\022>\n\014access_rig" +
      "ht\030\001 \001(\0132(.salto.nebula.accessright.v1.A" +
      "ccessRight\022/\n\005actor\030\002 \001(\0132 .salto.nebula" +
      ".event.v1.Principal\"\320\001\n\035AccessRightAcces" +
      "sPointCreated\022>\n\014access_right\030\001 \001(\0132(.sa" +
      "lto.nebula.accessright.v1.AccessRight\022>\n" +
      "\014access_point\030\002 \001(\0132(.salto.nebula.acces" +
      "spoint.v1.AccessPoint\022/\n\005actor\030\003 \001(\0132 .s" +
      "alto.nebula.event.v1.Principal\"\327\001\n#Acces" +
      "sRightAccessPointsBatchCreated\022>\n\014access" +
      "_right\030\001 \001(\0132(.salto.nebula.accessright." +
      "v1.AccessRight\022?\n\raccess_points\030\002 \003(\0132(." +
      "salto.nebula.accesspoint.v1.AccessPoint\022" +
      "/\n\005actor\030\003 \001(\0132 .salto.nebula.event.v1.P" +
      "rincipal\"\320\001\n\035AccessRightAccessPointDelet" +
      "ed\022>\n\014access_right\030\001 \001(\0132(.salto.nebula." +
      "accessright.v1.AccessRight\022>\n\014access_poi" +
      "nt\030\002 \001(\0132(.salto.nebula.accesspoint.v1.A" +
      "ccessPoint\022/\n\005actor\030\003 \001(\0132 .salto.nebula" +
      ".event.v1.Principal\"\327\001\n#AccessRightAcces" +
      "sPointsBatchDeleted\022>\n\014access_right\030\001 \001(" +
      "\0132(.salto.nebula.accessright.v1.AccessRi" +
      "ght\022?\n\raccess_points\030\002 \003(\0132(.salto.nebul" +
      "a.accesspoint.v1.AccessPoint\022/\n\005actor\030\003 " +
      "\001(\0132 .salto.nebula.event.v1.Principal\"h\n" +
      "\013UserCreated\022(\n\004user\030\001 \001(\0132\032.salto.nebul" +
      "a.user.v1.User\022/\n\005actor\030\002 \001(\0132 .salto.ne" +
      "bula.event.v1.Principal\"\250\001\n\013UserUpdated\022" +
      "(\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1.Use" +
      "r\022/\n\005actor\030\002 \001(\0132 .salto.nebula.event.v1" +
      ".Principal\022>\n\017previous_values\030\003 \001(\0132%.sa" +
      "lto.nebula.event.v1.PreviousValues\"h\n\013Us" +
      "erBlocked\022(\n\004user\030\001 \001(\0132\032.salto.nebula.u" +
      "ser.v1.User\022/\n\005actor\030\002 \001(\0132 .salto.nebul" +
      "a.event.v1.Principal\"j\n\rUserUnblocked\022(\n" +
      "\004user\030\001 \001(\0132\032.salto.nebula.user.v1.User\022" +
      "/\n\005actor\030\002 \001(\0132 .salto.nebula.event.v1.P" +
      "rincipal\"h\n\013UserDeleted\022(\n\004user\030\001 \001(\0132\032." +
      "salto.nebula.user.v1.User\022/\n\005actor\030\002 \001(\013" +
      "2 .salto.nebula.event.v1.Principal\"\263\001\n\026U" +
      "serAccessRightCreated\022(\n\004user\030\001 \001(\0132\032.sa" +
      "lto.nebula.user.v1.User\022>\n\014access_right\030" +
      "\002 \001(\0132(.salto.nebula.accessright.v1.Acce" +
      "ssRight\022/\n\005actor\030\003 \001(\0132 .salto.nebula.ev" +
      "ent.v1.Principal\"\263\001\n\026UserAccessRightUpda" +
      "ted\022(\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1" +
      ".User\022>\n\014access_right\030\002 \001(\0132(.salto.nebu" +
      "la.accessright.v1.AccessRight\022/\n\005actor\030\003" +
      " \001(\0132 .salto.nebula.event.v1.Principal\"\263" +
      "\001\n\026UserAccessRightDeleted\022(\n\004user\030\001 \001(\0132" +
      "\032.salto.nebula.user.v1.User\022>\n\014access_ri" +
      "ght\030\002 \001(\0132(.salto.nebula.accessright.v1." +
      "AccessRight\022/\n\005actor\030\003 \001(\0132 .salto.nebul" +
      "a.event.v1.Principal\"\235\001\n\017CardKeyAssigned" +
      "\022(\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1.Us" +
      "er\022/\n\010card_key\030\002 \001(\0132\035.salto.nebula.user" +
      ".v1.CardKey\022/\n\005actor\030\003 \001(\0132 .salto.nebul" +
      "a.event.v1.Principal\"\235\001\n\017CardKeyCanceled" +
      "\022(\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1.Us" +
      "er\022/\n\010card_key\030\002 \001(\0132\035.salto.nebula.user" +
      ".v1.CardKey\022/\n\005actor\030\003 \001(\0132 .salto.nebul" +
      "a.event.v1.Principal\"\232\001\n\016AppKeyAssigned\022" +
      "(\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1.Use" +
      "r\022-\n\007app_key\030\002 \001(\0132\034.salto.nebula.user.v" +
      "1.AppKey\022/\n\005actor\030\003 \001(\0132 .salto.nebula.e" +
      "vent.v1.Principal\"\232\001\n\016AppKeyCanceled\022(\n\004" +
      "user\030\001 \001(\0132\032.salto.nebula.user.v1.User\022-" +
      "\n\007app_key\030\002 \001(\0132\034.salto.nebula.user.v1.A" +
      "ppKey\022/\n\005actor\030\003 \001(\0132 .salto.nebula.even" +
      "t.v1.Principal\"\243\001\n\021WalletKeyAssigned\022(\n\004" +
      "user\030\001 \001(\0132\032.salto.nebula.user.v1.User\0223" +
      "\n\nwallet_key\030\002 \001(\0132\037.salto.nebula.user.v" +
      "1.WalletKey\022/\n\005actor\030\003 \001(\0132 .salto.nebul" +
      "a.event.v1.Principal\"\243\001\n\021WalletKeyCancel" +
      "ed\022(\n\004user\030\001 \001(\0132\032.salto.nebula.user.v1." +
      "User\0223\n\nwallet_key\030\002 \001(\0132\037.salto.nebula." +
      "user.v1.WalletKey\022/\n\005actor\030\003 \001(\0132 .salto" +
      ".nebula.event.v1.Principal\"h\n\013UnitMovedI" +
      "n\022(\n\004unit\030\001 \001(\0132\032.salto.nebula.unit.v1.U" +
      "nit\022/\n\005actor\030\002 \001(\0132 .salto.nebula.event." +
      "v1.Principal\"i\n\014UnitMovedOut\022(\n\004unit\030\001 \001" +
      "(\0132\032.salto.nebula.unit.v1.Unit\022/\n\005actor\030" +
      "\002 \001(\0132 .salto.nebula.event.v1.Principal\"" +
      "h\n\013UnitCreated\022(\n\004unit\030\001 \001(\0132\032.salto.neb" +
      "ula.unit.v1.Unit\022/\n\005actor\030\002 \001(\0132 .salto." +
      "nebula.event.v1.Principal\"\250\001\n\013UnitUpdate" +
      "d\022(\n\004unit\030\001 \001(\0132\032.salto.nebula.unit.v1.U" +
      "nit\022/\n\005actor\030\002 \001(\0132 .salto.nebula.event." +
      "v1.Principal\022>\n\017previous_values\030\003 \001(\0132%." +
      "salto.nebula.event.v1.PreviousValues\"h\n\013" +
      "UnitDeleted\022(\n\004unit\030\001 \001(\0132\032.salto.nebula" +
      ".unit.v1.Unit\022/\n\005actor\030\002 \001(\0132 .salto.neb" +
      "ula.event.v1.Principal\"\211\001\n\023EmergencyKeyC" +
      "reated\022A\n\remergency_key\030\001 \001(\0132*.salto.ne" +
      "bula.emergencykey.v1.EmergencyKey\022/\n\005act" +
      "or\030\002 \001(\0132 .salto.nebula.event.v1.Princip" +
      "al\"\311\001\n\023EmergencyKeyUpdated\022A\n\remergency_" +
      "key\030\001 \001(\0132*.salto.nebula.emergencykey.v1" +
      ".EmergencyKey\022/\n\005actor\030\002 \001(\0132 .salto.neb" +
      "ula.event.v1.Principal\022>\n\017previous_value" +
      "s\030\003 \001(\0132%.salto.nebula.event.v1.Previous" +
      "Values\"\211\001\n\023EmergencyKeyDeleted\022A\n\remerge" +
      "ncy_key\030\001 \001(\0132*.salto.nebula.emergencyke" +
      "y.v1.EmergencyKey\022/\n\005actor\030\002 \001(\0132 .salto" +
      ".nebula.event.v1.Principal\"\257\001\n\025Electroni" +
      "cKeyAssigned\022(\n\004user\030\001 \001(\0132\032.salto.nebul" +
      "a.user.v1.User\022;\n\016electronic_key\030\002 \001(\0132#" +
      ".salto.nebula.user.v1.ElectronicKey\022/\n\005a" +
      "ctor\030\003 \001(\0132 .salto.nebula.event.v1.Princ" +
      "ipal\"\257\001\n\025ElectronicKeyCanceled\022(\n\004user\030\001" +
      " \001(\0132\032.salto.nebula.user.v1.User\022;\n\016elec" +
      "tronic_key\030\002 \001(\0132#.salto.nebula.user.v1." +
      "ElectronicKey\022/\n\005actor\030\003 \001(\0132 .salto.neb" +
      "ula.event.v1.Principal\"\243\003\n\rAccessGranted" +
      "\022<\n\ncontroller\030\001 \001(\0132&.salto.nebula.cont" +
      "roller.v1.ControllerH\000\022(\n\004user\030\002 \001(\0132\032.s" +
      "alto.nebula.user.v1.User\022C\n\remergency_ke" +
      "y\030\003 \001(\0132*.salto.nebula.emergencykey.v1.E" +
      "mergencyKeyH\001\0221\n\010card_key\030\004 \001(\0132\035.salto." +
      "nebula.user.v1.CardKeyH\001\022/\n\007app_key\030\005 \001(" +
      "\0132\034.salto.nebula.user.v1.AppKeyH\001\0225\n\nwal" +
      "let_key\030\006 \001(\0132\037.salto.nebula.user.v1.Wal" +
      "letKeyH\001\0222\n\010passcode\030\007 \001(\0132\036.salto.nebul" +
      "a.user.v1.PasscodeH\001B\010\n\006deviceB\014\n\ncreden" +
      "tialB\317\001\n\035com.saltoapis.nebula.event.v1B\n" +
      "TypesProtoP\001Z@github.com/saltoapis-inter" +
      "nal/saltoapis-go/nebula/event/v1;event\252\002" +
      "\031Saltoapis.Nebula.Event.V1\312\002\031Saltoapis\\N" +
      "ebula\\Event\\V1\342\002%GPBMetadata\\Saltoapis\\N" +
      "ebula\\Event\\V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.saltoapis.nebula.accesspoint.v1.AccessPointProto.getDescriptor(),
          com.saltoapis.nebula.accessright.v1.AccessRightProto.getDescriptor(),
          com.saltoapis.nebula.controller.v1.ControllerProto.getDescriptor(),
          com.salto.nebula.emergencykey.v1.EmergencyKeyProto.getDescriptor(),
          com.saltoapis.nebula.unit.v1.UnitProto.getDescriptor(),
          com.saltoapis.nebula.user.v1.UserProto.getDescriptor(),
        });
    internal_static_salto_nebula_event_v1_Principal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_salto_nebula_event_v1_Principal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_Principal_descriptor,
        new java.lang.String[] { "User", "Type", });
    internal_static_salto_nebula_event_v1_PreviousValues_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_salto_nebula_event_v1_PreviousValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_PreviousValues_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_salto_nebula_event_v1_PreviousValues_ValuesEntry_descriptor =
      internal_static_salto_nebula_event_v1_PreviousValues_descriptor.getNestedTypes().get(0);
    internal_static_salto_nebula_event_v1_PreviousValues_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_PreviousValues_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_salto_nebula_event_v1_AccessPointCreated_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_salto_nebula_event_v1_AccessPointCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointCreated_descriptor,
        new java.lang.String[] { "AccessPoint", "Actor", });
    internal_static_salto_nebula_event_v1_AccessPointUpdated_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_salto_nebula_event_v1_AccessPointUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointUpdated_descriptor,
        new java.lang.String[] { "AccessPoint", "Actor", "PreviousValues", });
    internal_static_salto_nebula_event_v1_AccessPointDeleted_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_salto_nebula_event_v1_AccessPointDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointDeleted_descriptor,
        new java.lang.String[] { "AccessPoint", "Actor", });
    internal_static_salto_nebula_event_v1_AccessPointUnlocked_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_salto_nebula_event_v1_AccessPointUnlocked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointUnlocked_descriptor,
        new java.lang.String[] { "AccessPoint", "User", "EmergencyKey", "CardKey", "AppKey", "WalletKey", "Passcode", "Direction", "Credential", });
    internal_static_salto_nebula_event_v1_AccessPointLocked_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_salto_nebula_event_v1_AccessPointLocked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointLocked_descriptor,
        new java.lang.String[] { "AccessPoint", "User", "EmergencyKey", "CardKey", "AppKey", "WalletKey", "Passcode", "Credential", });
    internal_static_salto_nebula_event_v1_AccessPointForcedOpen_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_salto_nebula_event_v1_AccessPointForcedOpen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointForcedOpen_descriptor,
        new java.lang.String[] { "AccessPoint", });
    internal_static_salto_nebula_event_v1_AccessPointClosed_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_salto_nebula_event_v1_AccessPointClosed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointClosed_descriptor,
        new java.lang.String[] { "AccessPoint", });
    internal_static_salto_nebula_event_v1_AccessDenied_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_salto_nebula_event_v1_AccessDenied_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessDenied_descriptor,
        new java.lang.String[] { "AccessPoint", "User", "Reason", "EmergencyKey", "CardKey", "AppKey", "WalletKey", "Passcode", "Credential", });
    internal_static_salto_nebula_event_v1_AccessPointLeftOpen_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_salto_nebula_event_v1_AccessPointLeftOpen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessPointLeftOpen_descriptor,
        new java.lang.String[] { "AccessPoint", });
    internal_static_salto_nebula_event_v1_AccessRightCreated_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_salto_nebula_event_v1_AccessRightCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightCreated_descriptor,
        new java.lang.String[] { "AccessRight", "Actor", });
    internal_static_salto_nebula_event_v1_AccessRightUpdated_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_salto_nebula_event_v1_AccessRightUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightUpdated_descriptor,
        new java.lang.String[] { "AccessRight", "Actor", "PreviousValues", });
    internal_static_salto_nebula_event_v1_AccessRightDeleted_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_salto_nebula_event_v1_AccessRightDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightDeleted_descriptor,
        new java.lang.String[] { "AccessRight", "Actor", });
    internal_static_salto_nebula_event_v1_AccessRightAccessPointCreated_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_salto_nebula_event_v1_AccessRightAccessPointCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightAccessPointCreated_descriptor,
        new java.lang.String[] { "AccessRight", "AccessPoint", "Actor", });
    internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchCreated_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchCreated_descriptor,
        new java.lang.String[] { "AccessRight", "AccessPoints", "Actor", });
    internal_static_salto_nebula_event_v1_AccessRightAccessPointDeleted_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_salto_nebula_event_v1_AccessRightAccessPointDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightAccessPointDeleted_descriptor,
        new java.lang.String[] { "AccessRight", "AccessPoint", "Actor", });
    internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchDeleted_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessRightAccessPointsBatchDeleted_descriptor,
        new java.lang.String[] { "AccessRight", "AccessPoints", "Actor", });
    internal_static_salto_nebula_event_v1_UserCreated_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_salto_nebula_event_v1_UserCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserCreated_descriptor,
        new java.lang.String[] { "User", "Actor", });
    internal_static_salto_nebula_event_v1_UserUpdated_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_salto_nebula_event_v1_UserUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserUpdated_descriptor,
        new java.lang.String[] { "User", "Actor", "PreviousValues", });
    internal_static_salto_nebula_event_v1_UserBlocked_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_salto_nebula_event_v1_UserBlocked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserBlocked_descriptor,
        new java.lang.String[] { "User", "Actor", });
    internal_static_salto_nebula_event_v1_UserUnblocked_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_salto_nebula_event_v1_UserUnblocked_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserUnblocked_descriptor,
        new java.lang.String[] { "User", "Actor", });
    internal_static_salto_nebula_event_v1_UserDeleted_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_salto_nebula_event_v1_UserDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserDeleted_descriptor,
        new java.lang.String[] { "User", "Actor", });
    internal_static_salto_nebula_event_v1_UserAccessRightCreated_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_salto_nebula_event_v1_UserAccessRightCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserAccessRightCreated_descriptor,
        new java.lang.String[] { "User", "AccessRight", "Actor", });
    internal_static_salto_nebula_event_v1_UserAccessRightUpdated_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_salto_nebula_event_v1_UserAccessRightUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserAccessRightUpdated_descriptor,
        new java.lang.String[] { "User", "AccessRight", "Actor", });
    internal_static_salto_nebula_event_v1_UserAccessRightDeleted_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_salto_nebula_event_v1_UserAccessRightDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UserAccessRightDeleted_descriptor,
        new java.lang.String[] { "User", "AccessRight", "Actor", });
    internal_static_salto_nebula_event_v1_CardKeyAssigned_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_salto_nebula_event_v1_CardKeyAssigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_CardKeyAssigned_descriptor,
        new java.lang.String[] { "User", "CardKey", "Actor", });
    internal_static_salto_nebula_event_v1_CardKeyCanceled_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_salto_nebula_event_v1_CardKeyCanceled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_CardKeyCanceled_descriptor,
        new java.lang.String[] { "User", "CardKey", "Actor", });
    internal_static_salto_nebula_event_v1_AppKeyAssigned_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_salto_nebula_event_v1_AppKeyAssigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AppKeyAssigned_descriptor,
        new java.lang.String[] { "User", "AppKey", "Actor", });
    internal_static_salto_nebula_event_v1_AppKeyCanceled_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_salto_nebula_event_v1_AppKeyCanceled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AppKeyCanceled_descriptor,
        new java.lang.String[] { "User", "AppKey", "Actor", });
    internal_static_salto_nebula_event_v1_WalletKeyAssigned_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_salto_nebula_event_v1_WalletKeyAssigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_WalletKeyAssigned_descriptor,
        new java.lang.String[] { "User", "WalletKey", "Actor", });
    internal_static_salto_nebula_event_v1_WalletKeyCanceled_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_salto_nebula_event_v1_WalletKeyCanceled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_WalletKeyCanceled_descriptor,
        new java.lang.String[] { "User", "WalletKey", "Actor", });
    internal_static_salto_nebula_event_v1_UnitMovedIn_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_salto_nebula_event_v1_UnitMovedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UnitMovedIn_descriptor,
        new java.lang.String[] { "Unit", "Actor", });
    internal_static_salto_nebula_event_v1_UnitMovedOut_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_salto_nebula_event_v1_UnitMovedOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UnitMovedOut_descriptor,
        new java.lang.String[] { "Unit", "Actor", });
    internal_static_salto_nebula_event_v1_UnitCreated_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_salto_nebula_event_v1_UnitCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UnitCreated_descriptor,
        new java.lang.String[] { "Unit", "Actor", });
    internal_static_salto_nebula_event_v1_UnitUpdated_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_salto_nebula_event_v1_UnitUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UnitUpdated_descriptor,
        new java.lang.String[] { "Unit", "Actor", "PreviousValues", });
    internal_static_salto_nebula_event_v1_UnitDeleted_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_salto_nebula_event_v1_UnitDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_UnitDeleted_descriptor,
        new java.lang.String[] { "Unit", "Actor", });
    internal_static_salto_nebula_event_v1_EmergencyKeyCreated_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_salto_nebula_event_v1_EmergencyKeyCreated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_EmergencyKeyCreated_descriptor,
        new java.lang.String[] { "EmergencyKey", "Actor", });
    internal_static_salto_nebula_event_v1_EmergencyKeyUpdated_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_salto_nebula_event_v1_EmergencyKeyUpdated_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_EmergencyKeyUpdated_descriptor,
        new java.lang.String[] { "EmergencyKey", "Actor", "PreviousValues", });
    internal_static_salto_nebula_event_v1_EmergencyKeyDeleted_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_salto_nebula_event_v1_EmergencyKeyDeleted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_EmergencyKeyDeleted_descriptor,
        new java.lang.String[] { "EmergencyKey", "Actor", });
    internal_static_salto_nebula_event_v1_ElectronicKeyAssigned_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_salto_nebula_event_v1_ElectronicKeyAssigned_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_ElectronicKeyAssigned_descriptor,
        new java.lang.String[] { "User", "ElectronicKey", "Actor", });
    internal_static_salto_nebula_event_v1_ElectronicKeyCanceled_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_salto_nebula_event_v1_ElectronicKeyCanceled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_ElectronicKeyCanceled_descriptor,
        new java.lang.String[] { "User", "ElectronicKey", "Actor", });
    internal_static_salto_nebula_event_v1_AccessGranted_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_salto_nebula_event_v1_AccessGranted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_salto_nebula_event_v1_AccessGranted_descriptor,
        new java.lang.String[] { "Controller", "User", "EmergencyKey", "CardKey", "AppKey", "WalletKey", "Passcode", "Device", "Credential", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
    com.saltoapis.nebula.accesspoint.v1.AccessPointProto.getDescriptor();
    com.saltoapis.nebula.accessright.v1.AccessRightProto.getDescriptor();
    com.saltoapis.nebula.controller.v1.ControllerProto.getDescriptor();
    com.salto.nebula.emergencykey.v1.EmergencyKeyProto.getDescriptor();
    com.saltoapis.nebula.unit.v1.UnitProto.getDescriptor();
    com.saltoapis.nebula.user.v1.UserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
