// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/installation/v1/installation.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.installation.v1;

@com.google.protobuf.Generated
public interface InstallationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.installation.v1.Installation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the installation. It must have the format
   * of `installations/&#42;`. For example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Resource name of the installation. It must have the format
   * of `installations/&#42;`. For example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Display name of the installation.
   * </pre>
   *
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <pre>
   * Display name of the installation.
   * </pre>
   *
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <pre>
   * The file resource name for the installation photo. It must have the
   * format of
   * `installations/surelock-homes-hq/files/01DSYSJ1PR36VVC3MRFRV4DC7G`.
   * </pre>
   *
   * <code>optional string photo = 3;</code>
   * @return Whether the photo field is set.
   */
  boolean hasPhoto();
  /**
   * <pre>
   * The file resource name for the installation photo. It must have the
   * format of
   * `installations/surelock-homes-hq/files/01DSYSJ1PR36VVC3MRFRV4DC7G`.
   * </pre>
   *
   * <code>optional string photo = 3;</code>
   * @return The photo.
   */
  java.lang.String getPhoto();
  /**
   * <pre>
   * The file resource name for the installation photo. It must have the
   * format of
   * `installations/surelock-homes-hq/files/01DSYSJ1PR36VVC3MRFRV4DC7G`.
   * </pre>
   *
   * <code>optional string photo = 3;</code>
   * @return The bytes for photo.
   */
  com.google.protobuf.ByteString
      getPhotoBytes();

  /**
   * <pre>
   * The URI to view the installation photo.
   * </pre>
   *
   * <code>string photo_uri = 4;</code>
   * @return The photoUri.
   */
  java.lang.String getPhotoUri();
  /**
   * <pre>
   * The URI to view the installation photo.
   * </pre>
   *
   * <code>string photo_uri = 4;</code>
   * @return The bytes for photoUri.
   */
  com.google.protobuf.ByteString
      getPhotoUriBytes();

  /**
   * <pre>
   * Unstructured address.
   *
   * For example: "1600 Amphitheatre Pkwy, Mountain View, CA 94043,
   * Sunnyvale, California."
   * </pre>
   *
   * <code>string address = 5;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <pre>
   * Unstructured address.
   *
   * For example: "1600 Amphitheatre Pkwy, Mountain View, CA 94043,
   * Sunnyvale, California."
   * </pre>
   *
   * <code>string address = 5;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <pre>
   * Time zone where the installation is located. It must follow the IANA Time
   * Zone Database format. For example, "America/New_York."
   * </pre>
   *
   * <code>string time_zone = 6;</code>
   * @return The timeZone.
   */
  java.lang.String getTimeZone();
  /**
   * <pre>
   * Time zone where the installation is located. It must follow the IANA Time
   * Zone Database format. For example, "America/New_York."
   * </pre>
   *
   * <code>string time_zone = 6;</code>
   * @return The bytes for timeZone.
   */
  com.google.protobuf.ByteString
      getTimeZoneBytes();

  /**
   * <pre>
   * The digital key art configuration resource that belongs to the installation.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.Installation.DigitalKeyArt digital_key_art = 7;</code>
   * @return Whether the digitalKeyArt field is set.
   */
  boolean hasDigitalKeyArt();
  /**
   * <pre>
   * The digital key art configuration resource that belongs to the installation.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.Installation.DigitalKeyArt digital_key_art = 7;</code>
   * @return The digitalKeyArt.
   */
  com.saltoapis.nebula.installation.v1.Installation.DigitalKeyArt getDigitalKeyArt();
  /**
   * <pre>
   * The digital key art configuration resource that belongs to the installation.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.Installation.DigitalKeyArt digital_key_art = 7;</code>
   */
  com.saltoapis.nebula.installation.v1.Installation.DigitalKeyArtOrBuilder getDigitalKeyArtOrBuilder();

  /**
   * <pre>
   * Current state of the ownership transfer. Client must not set the
   * `Installation.transfer_ownership_state` field. This data is only
   * visible to the current installation owner.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.Installation.TransferOwnershipState transfer_ownership_state = 8;</code>
   * @return Whether the transferOwnershipState field is set.
   */
  boolean hasTransferOwnershipState();
  /**
   * <pre>
   * Current state of the ownership transfer. Client must not set the
   * `Installation.transfer_ownership_state` field. This data is only
   * visible to the current installation owner.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.Installation.TransferOwnershipState transfer_ownership_state = 8;</code>
   * @return The transferOwnershipState.
   */
  com.saltoapis.nebula.installation.v1.Installation.TransferOwnershipState getTransferOwnershipState();
  /**
   * <pre>
   * Current state of the ownership transfer. Client must not set the
   * `Installation.transfer_ownership_state` field. This data is only
   * visible to the current installation owner.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.Installation.TransferOwnershipState transfer_ownership_state = 8;</code>
   */
  com.saltoapis.nebula.installation.v1.Installation.TransferOwnershipStateOrBuilder getTransferOwnershipStateOrBuilder();

  /**
   * <pre>
   * The time when the installation was soft deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 12;</code>
   * @return Whether the deleteTime field is set.
   */
  boolean hasDeleteTime();
  /**
   * <pre>
   * The time when the installation was soft deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 12;</code>
   * @return The deleteTime.
   */
  com.google.protobuf.Timestamp getDeleteTime();
  /**
   * <pre>
   * The time when the installation was soft deleted.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp delete_time = 12;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeleteTimeOrBuilder();

  /**
   * <pre>
   * The information of the partner who created the installation.
   * </pre>
   *
   * <code>optional .salto.nebula.installation.v1.Installation.PartnerInfo partner_info = 9;</code>
   * @return Whether the partnerInfo field is set.
   */
  boolean hasPartnerInfo();
  /**
   * <pre>
   * The information of the partner who created the installation.
   * </pre>
   *
   * <code>optional .salto.nebula.installation.v1.Installation.PartnerInfo partner_info = 9;</code>
   * @return The partnerInfo.
   */
  com.saltoapis.nebula.installation.v1.Installation.PartnerInfo getPartnerInfo();
  /**
   * <pre>
   * The information of the partner who created the installation.
   * </pre>
   *
   * <code>optional .salto.nebula.installation.v1.Installation.PartnerInfo partner_info = 9;</code>
   */
  com.saltoapis.nebula.installation.v1.Installation.PartnerInfoOrBuilder getPartnerInfoOrBuilder();

  /**
   * <pre>
   * The time when the installation was blocked.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp block_time = 11;</code>
   * @return Whether the blockTime field is set.
   */
  boolean hasBlockTime();
  /**
   * <pre>
   * The time when the installation was blocked.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp block_time = 11;</code>
   * @return The blockTime.
   */
  com.google.protobuf.Timestamp getBlockTime();
  /**
   * <pre>
   * The time when the installation was blocked.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp block_time = 11;</code>
   */
  com.google.protobuf.TimestampOrBuilder getBlockTimeOrBuilder();

  /**
   * <pre>
   * The length of time a key remains valid before requiring renewal. This
   * duration defines the effective lifespan of a key, after which it must be
   * updated to maintain access privileges. The duration is crucial for
   * ensuring security in the system, as it determines how frequently keys
   * need to be renewed.
   * </pre>
   *
   * <code>.google.protobuf.Duration key_renewal_duration = 10;</code>
   * @return Whether the keyRenewalDuration field is set.
   */
  boolean hasKeyRenewalDuration();
  /**
   * <pre>
   * The length of time a key remains valid before requiring renewal. This
   * duration defines the effective lifespan of a key, after which it must be
   * updated to maintain access privileges. The duration is crucial for
   * ensuring security in the system, as it determines how frequently keys
   * need to be renewed.
   * </pre>
   *
   * <code>.google.protobuf.Duration key_renewal_duration = 10;</code>
   * @return The keyRenewalDuration.
   */
  com.google.protobuf.Duration getKeyRenewalDuration();
  /**
   * <pre>
   * The length of time a key remains valid before requiring renewal. This
   * duration defines the effective lifespan of a key, after which it must be
   * updated to maintain access privileges. The duration is crucial for
   * ensuring security in the system, as it determines how frequently keys
   * need to be renewed.
   * </pre>
   *
   * <code>.google.protobuf.Duration key_renewal_duration = 10;</code>
   */
  com.google.protobuf.DurationOrBuilder getKeyRenewalDurationOrBuilder();
}
