// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/installation/v1/installation.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.installation.v1;

public interface ListInvoicesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.installation.v1.ListInvoicesRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The parent resource name. It must have the format of
   * `installations/&#42;&#47;subscription`. For example: `installations/surelock-homes-hq/subscription`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * The parent resource name. It must have the format of
   * `installations/&#42;&#47;subscription`. For example: `installations/surelock-homes-hq/subscription`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();
}
