// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/installation/v1/installation.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.installation.v1;

/**
 * <pre>
 * (-- api-linter: core::0134::request-mask-required=disabled
 * aip.dev/not-precedent: We need to do this to simplify the update operation. --)
 * The request message for [`UpdateBillingInfo`][salto.nebula.installation.v1.InstallationService.UpdateBillingInfo]
 * </pre>
 *
 * Protobuf type {@code salto.nebula.installation.v1.UpdateBillingInfoRequest}
 */
@com.google.protobuf.Generated
public final class UpdateBillingInfoRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:salto.nebula.installation.v1.UpdateBillingInfoRequest)
    UpdateBillingInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "UpdateBillingInfoRequest");
  }
  // Use UpdateBillingInfoRequest.newBuilder() to construct.
  private UpdateBillingInfoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UpdateBillingInfoRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.saltoapis.nebula.installation.v1.InstallationProto.internal_static_salto_nebula_installation_v1_UpdateBillingInfoRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.saltoapis.nebula.installation.v1.InstallationProto.internal_static_salto_nebula_installation_v1_UpdateBillingInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.class, com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.Builder.class);
  }

  private int bitField0_;
  public static final int BILLING_INFO_FIELD_NUMBER = 1;
  private com.saltoapis.nebula.installation.v1.BillingInfo billingInfo_;
  /**
   * <pre>
   * The billing info resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
   * @return Whether the billingInfo field is set.
   */
  @java.lang.Override
  public boolean hasBillingInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The billing info resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
   * @return The billingInfo.
   */
  @java.lang.Override
  public com.saltoapis.nebula.installation.v1.BillingInfo getBillingInfo() {
    return billingInfo_ == null ? com.saltoapis.nebula.installation.v1.BillingInfo.getDefaultInstance() : billingInfo_;
  }
  /**
   * <pre>
   * The billing info resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
   */
  @java.lang.Override
  public com.saltoapis.nebula.installation.v1.BillingInfoOrBuilder getBillingInfoOrBuilder() {
    return billingInfo_ == null ? com.saltoapis.nebula.installation.v1.BillingInfo.getDefaultInstance() : billingInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBillingInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBillingInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest)) {
      return super.equals(obj);
    }
    com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest other = (com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest) obj;

    if (hasBillingInfo() != other.hasBillingInfo()) return false;
    if (hasBillingInfo()) {
      if (!getBillingInfo()
          .equals(other.getBillingInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBillingInfo()) {
      hash = (37 * hash) + BILLING_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getBillingInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * (-- api-linter: core::0134::request-mask-required=disabled
   * aip.dev/not-precedent: We need to do this to simplify the update operation. --)
   * The request message for [`UpdateBillingInfo`][salto.nebula.installation.v1.InstallationService.UpdateBillingInfo]
   * </pre>
   *
   * Protobuf type {@code salto.nebula.installation.v1.UpdateBillingInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.installation.v1.UpdateBillingInfoRequest)
      com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.saltoapis.nebula.installation.v1.InstallationProto.internal_static_salto_nebula_installation_v1_UpdateBillingInfoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.saltoapis.nebula.installation.v1.InstallationProto.internal_static_salto_nebula_installation_v1_UpdateBillingInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.class, com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.Builder.class);
    }

    // Construct using com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetBillingInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      billingInfo_ = null;
      if (billingInfoBuilder_ != null) {
        billingInfoBuilder_.dispose();
        billingInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.saltoapis.nebula.installation.v1.InstallationProto.internal_static_salto_nebula_installation_v1_UpdateBillingInfoRequest_descriptor;
    }

    @java.lang.Override
    public com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest getDefaultInstanceForType() {
      return com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest build() {
      com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest buildPartial() {
      com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest result = new com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.billingInfo_ = billingInfoBuilder_ == null
            ? billingInfo_
            : billingInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest) {
        return mergeFrom((com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest other) {
      if (other == com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest.getDefaultInstance()) return this;
      if (other.hasBillingInfo()) {
        mergeBillingInfo(other.getBillingInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetBillingInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.saltoapis.nebula.installation.v1.BillingInfo billingInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        com.saltoapis.nebula.installation.v1.BillingInfo, com.saltoapis.nebula.installation.v1.BillingInfo.Builder, com.saltoapis.nebula.installation.v1.BillingInfoOrBuilder> billingInfoBuilder_;
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     * @return Whether the billingInfo field is set.
     */
    public boolean hasBillingInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     * @return The billingInfo.
     */
    public com.saltoapis.nebula.installation.v1.BillingInfo getBillingInfo() {
      if (billingInfoBuilder_ == null) {
        return billingInfo_ == null ? com.saltoapis.nebula.installation.v1.BillingInfo.getDefaultInstance() : billingInfo_;
      } else {
        return billingInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    public Builder setBillingInfo(com.saltoapis.nebula.installation.v1.BillingInfo value) {
      if (billingInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        billingInfo_ = value;
      } else {
        billingInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    public Builder setBillingInfo(
        com.saltoapis.nebula.installation.v1.BillingInfo.Builder builderForValue) {
      if (billingInfoBuilder_ == null) {
        billingInfo_ = builderForValue.build();
      } else {
        billingInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    public Builder mergeBillingInfo(com.saltoapis.nebula.installation.v1.BillingInfo value) {
      if (billingInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          billingInfo_ != null &&
          billingInfo_ != com.saltoapis.nebula.installation.v1.BillingInfo.getDefaultInstance()) {
          getBillingInfoBuilder().mergeFrom(value);
        } else {
          billingInfo_ = value;
        }
      } else {
        billingInfoBuilder_.mergeFrom(value);
      }
      if (billingInfo_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    public Builder clearBillingInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      billingInfo_ = null;
      if (billingInfoBuilder_ != null) {
        billingInfoBuilder_.dispose();
        billingInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    public com.saltoapis.nebula.installation.v1.BillingInfo.Builder getBillingInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetBillingInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    public com.saltoapis.nebula.installation.v1.BillingInfoOrBuilder getBillingInfoOrBuilder() {
      if (billingInfoBuilder_ != null) {
        return billingInfoBuilder_.getMessageOrBuilder();
      } else {
        return billingInfo_ == null ?
            com.saltoapis.nebula.installation.v1.BillingInfo.getDefaultInstance() : billingInfo_;
      }
    }
    /**
     * <pre>
     * The billing info resource which replaces the resource on the server.
     * </pre>
     *
     * <code>.salto.nebula.installation.v1.BillingInfo billing_info = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.saltoapis.nebula.installation.v1.BillingInfo, com.saltoapis.nebula.installation.v1.BillingInfo.Builder, com.saltoapis.nebula.installation.v1.BillingInfoOrBuilder> 
        internalGetBillingInfoFieldBuilder() {
      if (billingInfoBuilder_ == null) {
        billingInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.saltoapis.nebula.installation.v1.BillingInfo, com.saltoapis.nebula.installation.v1.BillingInfo.Builder, com.saltoapis.nebula.installation.v1.BillingInfoOrBuilder>(
                getBillingInfo(),
                getParentForChildren(),
                isClean());
        billingInfo_ = null;
      }
      return billingInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.installation.v1.UpdateBillingInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:salto.nebula.installation.v1.UpdateBillingInfoRequest)
  private static final com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest();
  }

  public static com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateBillingInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateBillingInfoRequest>() {
    @java.lang.Override
    public UpdateBillingInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateBillingInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UpdateBillingInfoRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.saltoapis.nebula.installation.v1.UpdateBillingInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

