// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/installation/v1/installation.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.installation.v1;

public interface UpdateCardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.installation.v1.UpdateCardResponse)
    com.google.protobuf.MessageLiteOrBuilder {
}
