// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/accessright/v1/access_right.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.accessright.v1;

public interface UpdateAccessRightAccessPointRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.accessright.v1.UpdateAccessRightAccessPointRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The access right's access point resource which replaces the resource on
   * the server.
   * </pre>
   *
   * <code>.salto.nebula.accessright.v1.AccessRightAccessPoint access_right_access_point = 1;</code>
   * @return Whether the accessRightAccessPoint field is set.
   */
  boolean hasAccessRightAccessPoint();
  /**
   * <pre>
   * The access right's access point resource which replaces the resource on
   * the server.
   * </pre>
   *
   * <code>.salto.nebula.accessright.v1.AccessRightAccessPoint access_right_access_point = 1;</code>
   * @return The accessRightAccessPoint.
   */
  com.saltoapis.nebula.accessright.v1.AccessRightAccessPoint getAccessRightAccessPoint();
  /**
   * <pre>
   * The access right's access point resource which replaces the resource on
   * the server.
   * </pre>
   *
   * <code>.salto.nebula.accessright.v1.AccessRightAccessPoint access_right_access_point = 1;</code>
   */
  com.saltoapis.nebula.accessright.v1.AccessRightAccessPointOrBuilder getAccessRightAccessPointOrBuilder();

  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
