// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/controller/v1/controller.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.controller.v1;

public interface BindControllerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.controller.v1.BindControllerResponse)
    com.google.protobuf.MessageLiteOrBuilder {
}
