// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/controller/v1/controller.proto

// Protobuf Java Version: 4.26.1
package com.saltoapis.nebula.controller.v1;

public interface UnbindControllerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.controller.v1.UnbindControllerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource name of the controller to be bound. For example:
   * `installations/surelock-homes-hq/controllers/main-controller`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The resource name of the controller to be bound. For example:
   * `installations/surelock-homes-hq/controllers/main-controller`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * If set to true, the device identifier is removed (unbound) from the
   * controller. Otherwise, the request will only work if the controller
   * isn't bound to any previous device identifier.
   * </pre>
   *
   * <code>bool force = 2;</code>
   * @return The force.
   */
  boolean getForce();
}
