// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/extender/v1/extender.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.extender.v1;

@com.google.protobuf.Generated
public interface BindExtenderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.extender.v1.BindExtenderResponse)
    com.google.protobuf.MessageOrBuilder {
}
