// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/extender/v1/extender.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.extender.v1;

public interface UpdateExtenderFirmwareRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.extender.v1.UpdateExtenderFirmwareRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource name of the extender whose firmware will be updated, for
   * example:
   * `installations/surelock-homes-hq/extenders/elementary`.
   * </pre>
   *
   * <code>string extender = 1;</code>
   * @return The extender.
   */
  java.lang.String getExtender();
  /**
   * <pre>
   * The resource name of the extender whose firmware will be updated, for
   * example:
   * `installations/surelock-homes-hq/extenders/elementary`.
   * </pre>
   *
   * <code>string extender = 1;</code>
   * @return The bytes for extender.
   */
  com.google.protobuf.ByteString
      getExtenderBytes();
}
