// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/electroniclock/v1/electronic_lock.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.nebula.electroniclock.v1;

@com.google.protobuf.Generated
public interface GenerateAuthorizationTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.electroniclock.v1.GenerateAuthorizationTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Authorization token to be used for connecting to an electronic lock.
   * </pre>
   *
   * <code>bytes authorization_token = 1;</code>
   * @return The authorizationToken.
   */
  com.google.protobuf.ByteString getAuthorizationToken();
}
