// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/destination/v1/destination.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.destination.v1;

public interface BatchGetDestinationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.destination.v1.BatchGetDestinationsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Resource name of the parent of the destinations to be retreived.
   * For example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   * <pre>
   * Resource name of the parent of the destinations to be retreived.
   * For example: `installations/surelock-homes-hq`.
   * </pre>
   *
   * <code>string parent = 1;</code>
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString
      getParentBytes();

  /**
   * <pre>
   * The names of the destinations requested.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   * @return A list containing the names.
   */
  java.util.List<java.lang.String>
      getNamesList();
  /**
   * <pre>
   * The names of the destinations requested.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   * @return The count of names.
   */
  int getNamesCount();
  /**
   * <pre>
   * The names of the destinations requested.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   * @param index The index of the element to return.
   * @return The names at the given index.
   */
  java.lang.String getNames(int index);
  /**
   * <pre>
   * The names of the destinations requested.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the names at the given index.
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);
}
