// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/destination/v1/destination.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.destination.v1;

public interface DeleteDestinationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.destination.v1.DeleteDestinationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The resource name of the destination to be deleted, for example:
   * `installations/surelock-homes-hq/destinations/floor1`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The resource name of the destination to be deleted, for example:
   * `installations/surelock-homes-hq/destinations/floor1`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
