// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/calendar/v1/calendar.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.calendar.v1;

/**
 * Protobuf type {@code salto.nebula.calendar.v1.Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:salto.nebula.calendar.v1.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 2,
      /* suffix= */ "",
      Event.class.getName());
  }
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    name_ = "";
    dayType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.saltoapis.nebula.calendar.v1.CalendarProto.internal_static_salto_nebula_calendar_v1_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.saltoapis.nebula.calendar.v1.CalendarProto.internal_static_salto_nebula_calendar_v1_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.saltoapis.nebula.calendar.v1.Event.class, com.saltoapis.nebula.calendar.v1.Event.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * Output only. Resource name of the calendar event. It must have the
   * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
   * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Output only. Resource name of the calendar event. It must have the
   * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
   * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DAY_TYPE_FIELD_NUMBER = 2;
  private int dayType_ = 0;
  /**
   * <pre>
   * Day type.
   * </pre>
   *
   * <code>.salto.nebula.type.DayType day_type = 2;</code>
   * @return The enum numeric value on the wire for dayType.
   */
  @java.lang.Override public int getDayTypeValue() {
    return dayType_;
  }
  /**
   * <pre>
   * Day type.
   * </pre>
   *
   * <code>.salto.nebula.type.DayType day_type = 2;</code>
   * @return The dayType.
   */
  @java.lang.Override public com.saltoapis.nebula.type.DayType getDayType() {
    com.saltoapis.nebula.type.DayType result = com.saltoapis.nebula.type.DayType.forNumber(dayType_);
    return result == null ? com.saltoapis.nebula.type.DayType.UNRECOGNIZED : result;
  }

  public static final int START_DATE_FIELD_NUMBER = 3;
  private com.saltoapis.type.Date startDate_;
  /**
   * <pre>
   * Start date.
   * </pre>
   *
   * <code>.salto.type.Date start_date = 3;</code>
   * @return Whether the startDate field is set.
   */
  @java.lang.Override
  public boolean hasStartDate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Start date.
   * </pre>
   *
   * <code>.salto.type.Date start_date = 3;</code>
   * @return The startDate.
   */
  @java.lang.Override
  public com.saltoapis.type.Date getStartDate() {
    return startDate_ == null ? com.saltoapis.type.Date.getDefaultInstance() : startDate_;
  }
  /**
   * <pre>
   * Start date.
   * </pre>
   *
   * <code>.salto.type.Date start_date = 3;</code>
   */
  @java.lang.Override
  public com.saltoapis.type.DateOrBuilder getStartDateOrBuilder() {
    return startDate_ == null ? com.saltoapis.type.Date.getDefaultInstance() : startDate_;
  }

  public static final int END_DATE_FIELD_NUMBER = 4;
  private com.saltoapis.type.Date endDate_;
  /**
   * <pre>
   * End date.
   * </pre>
   *
   * <code>.salto.type.Date end_date = 4;</code>
   * @return Whether the endDate field is set.
   */
  @java.lang.Override
  public boolean hasEndDate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * End date.
   * </pre>
   *
   * <code>.salto.type.Date end_date = 4;</code>
   * @return The endDate.
   */
  @java.lang.Override
  public com.saltoapis.type.Date getEndDate() {
    return endDate_ == null ? com.saltoapis.type.Date.getDefaultInstance() : endDate_;
  }
  /**
   * <pre>
   * End date.
   * </pre>
   *
   * <code>.salto.type.Date end_date = 4;</code>
   */
  @java.lang.Override
  public com.saltoapis.type.DateOrBuilder getEndDateOrBuilder() {
    return endDate_ == null ? com.saltoapis.type.Date.getDefaultInstance() : endDate_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (dayType_ != com.saltoapis.nebula.type.DayType.DAY_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, dayType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getStartDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getEndDate());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (dayType_ != com.saltoapis.nebula.type.DayType.DAY_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, dayType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStartDate());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getEndDate());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.saltoapis.nebula.calendar.v1.Event)) {
      return super.equals(obj);
    }
    com.saltoapis.nebula.calendar.v1.Event other = (com.saltoapis.nebula.calendar.v1.Event) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (dayType_ != other.dayType_) return false;
    if (hasStartDate() != other.hasStartDate()) return false;
    if (hasStartDate()) {
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
    }
    if (hasEndDate() != other.hasEndDate()) return false;
    if (hasEndDate()) {
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DAY_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + dayType_;
    if (hasStartDate()) {
      hash = (37 * hash) + START_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + END_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.calendar.v1.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.saltoapis.nebula.calendar.v1.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saltoapis.nebula.calendar.v1.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.calendar.v1.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code salto.nebula.calendar.v1.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.calendar.v1.Event)
      com.saltoapis.nebula.calendar.v1.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.saltoapis.nebula.calendar.v1.CalendarProto.internal_static_salto_nebula_calendar_v1_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.saltoapis.nebula.calendar.v1.CalendarProto.internal_static_salto_nebula_calendar_v1_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.saltoapis.nebula.calendar.v1.Event.class, com.saltoapis.nebula.calendar.v1.Event.Builder.class);
    }

    // Construct using com.saltoapis.nebula.calendar.v1.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getStartDateFieldBuilder();
        getEndDateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      dayType_ = 0;
      startDate_ = null;
      if (startDateBuilder_ != null) {
        startDateBuilder_.dispose();
        startDateBuilder_ = null;
      }
      endDate_ = null;
      if (endDateBuilder_ != null) {
        endDateBuilder_.dispose();
        endDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.saltoapis.nebula.calendar.v1.CalendarProto.internal_static_salto_nebula_calendar_v1_Event_descriptor;
    }

    @java.lang.Override
    public com.saltoapis.nebula.calendar.v1.Event getDefaultInstanceForType() {
      return com.saltoapis.nebula.calendar.v1.Event.getDefaultInstance();
    }

    @java.lang.Override
    public com.saltoapis.nebula.calendar.v1.Event build() {
      com.saltoapis.nebula.calendar.v1.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.saltoapis.nebula.calendar.v1.Event buildPartial() {
      com.saltoapis.nebula.calendar.v1.Event result = new com.saltoapis.nebula.calendar.v1.Event(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.saltoapis.nebula.calendar.v1.Event result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dayType_ = dayType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.startDate_ = startDateBuilder_ == null
            ? startDate_
            : startDateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.endDate_ = endDateBuilder_ == null
            ? endDate_
            : endDateBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.saltoapis.nebula.calendar.v1.Event) {
        return mergeFrom((com.saltoapis.nebula.calendar.v1.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.saltoapis.nebula.calendar.v1.Event other) {
      if (other == com.saltoapis.nebula.calendar.v1.Event.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.dayType_ != 0) {
        setDayTypeValue(other.getDayTypeValue());
      }
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              dayType_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getStartDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getEndDateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Output only. Resource name of the calendar event. It must have the
     * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
     * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Output only. Resource name of the calendar event. It must have the
     * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
     * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Output only. Resource name of the calendar event. It must have the
     * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
     * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. Resource name of the calendar event. It must have the
     * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
     * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Output only. Resource name of the calendar event. It must have the
     * format of `installations/&#42;&#47;calendars/&#42;&#47;events/&#42;`. For example:
     * `installations/surelock-homes-hq/calendars/gmt/events/twelvetide`.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int dayType_ = 0;
    /**
     * <pre>
     * Day type.
     * </pre>
     *
     * <code>.salto.nebula.type.DayType day_type = 2;</code>
     * @return The enum numeric value on the wire for dayType.
     */
    @java.lang.Override public int getDayTypeValue() {
      return dayType_;
    }
    /**
     * <pre>
     * Day type.
     * </pre>
     *
     * <code>.salto.nebula.type.DayType day_type = 2;</code>
     * @param value The enum numeric value on the wire for dayType to set.
     * @return This builder for chaining.
     */
    public Builder setDayTypeValue(int value) {
      dayType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Day type.
     * </pre>
     *
     * <code>.salto.nebula.type.DayType day_type = 2;</code>
     * @return The dayType.
     */
    @java.lang.Override
    public com.saltoapis.nebula.type.DayType getDayType() {
      com.saltoapis.nebula.type.DayType result = com.saltoapis.nebula.type.DayType.forNumber(dayType_);
      return result == null ? com.saltoapis.nebula.type.DayType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Day type.
     * </pre>
     *
     * <code>.salto.nebula.type.DayType day_type = 2;</code>
     * @param value The dayType to set.
     * @return This builder for chaining.
     */
    public Builder setDayType(com.saltoapis.nebula.type.DayType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      dayType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Day type.
     * </pre>
     *
     * <code>.salto.nebula.type.DayType day_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDayType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dayType_ = 0;
      onChanged();
      return this;
    }

    private com.saltoapis.type.Date startDate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.saltoapis.type.Date, com.saltoapis.type.Date.Builder, com.saltoapis.type.DateOrBuilder> startDateBuilder_;
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     * @return Whether the startDate field is set.
     */
    public boolean hasStartDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     * @return The startDate.
     */
    public com.saltoapis.type.Date getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.saltoapis.type.Date.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    public Builder setStartDate(com.saltoapis.type.Date value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
      } else {
        startDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    public Builder setStartDate(
        com.saltoapis.type.Date.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    public Builder mergeStartDate(com.saltoapis.type.Date value) {
      if (startDateBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          startDate_ != null &&
          startDate_ != com.saltoapis.type.Date.getDefaultInstance()) {
          getStartDateBuilder().mergeFrom(value);
        } else {
          startDate_ = value;
        }
      } else {
        startDateBuilder_.mergeFrom(value);
      }
      if (startDate_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    public Builder clearStartDate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      startDate_ = null;
      if (startDateBuilder_ != null) {
        startDateBuilder_.dispose();
        startDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    public com.saltoapis.type.Date.Builder getStartDateBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    public com.saltoapis.type.DateOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.saltoapis.type.Date.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <pre>
     * Start date.
     * </pre>
     *
     * <code>.salto.type.Date start_date = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.saltoapis.type.Date, com.saltoapis.type.Date.Builder, com.saltoapis.type.DateOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.saltoapis.type.Date, com.saltoapis.type.Date.Builder, com.saltoapis.type.DateOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.saltoapis.type.Date endDate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.saltoapis.type.Date, com.saltoapis.type.Date.Builder, com.saltoapis.type.DateOrBuilder> endDateBuilder_;
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     * @return Whether the endDate field is set.
     */
    public boolean hasEndDate() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     * @return The endDate.
     */
    public com.saltoapis.type.Date getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.saltoapis.type.Date.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    public Builder setEndDate(com.saltoapis.type.Date value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
      } else {
        endDateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    public Builder setEndDate(
        com.saltoapis.type.Date.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    public Builder mergeEndDate(com.saltoapis.type.Date value) {
      if (endDateBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          endDate_ != null &&
          endDate_ != com.saltoapis.type.Date.getDefaultInstance()) {
          getEndDateBuilder().mergeFrom(value);
        } else {
          endDate_ = value;
        }
      } else {
        endDateBuilder_.mergeFrom(value);
      }
      if (endDate_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    public Builder clearEndDate() {
      bitField0_ = (bitField0_ & ~0x00000008);
      endDate_ = null;
      if (endDateBuilder_ != null) {
        endDateBuilder_.dispose();
        endDateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    public com.saltoapis.type.Date.Builder getEndDateBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getEndDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    public com.saltoapis.type.DateOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.saltoapis.type.Date.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <pre>
     * End date.
     * </pre>
     *
     * <code>.salto.type.Date end_date = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.saltoapis.type.Date, com.saltoapis.type.Date.Builder, com.saltoapis.type.DateOrBuilder> 
        getEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.saltoapis.type.Date, com.saltoapis.type.Date.Builder, com.saltoapis.type.DateOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.calendar.v1.Event)
  }

  // @@protoc_insertion_point(class_scope:salto.nebula.calendar.v1.Event)
  private static final com.saltoapis.nebula.calendar.v1.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.saltoapis.nebula.calendar.v1.Event();
  }

  public static com.saltoapis.nebula.calendar.v1.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.saltoapis.nebula.calendar.v1.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

