// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: salto/nebula/iam/v1/iam.proto

// Protobuf Java Version: 3.25.1
package com.saltoapis.nebula.iam.v1;

/**
 * <pre>
 * The response message for [`ListRoles`][salto.nebula.iam.v1.IAMService.ListRoles]
 * </pre>
 *
 * Protobuf type {@code salto.nebula.iam.v1.ListRolesResponse}
 */
public  final class ListRolesResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListRolesResponse, ListRolesResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:salto.nebula.iam.v1.ListRolesResponse)
    ListRolesResponseOrBuilder {
  private ListRolesResponse() {
    roles_ = emptyProtobufList();
    nextPageToken_ = "";
  }
  public static final int ROLES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.saltoapis.nebula.iam.v1.Role> roles_;
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.saltoapis.nebula.iam.v1.Role> getRolesList() {
    return roles_;
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  public java.util.List<? extends com.saltoapis.nebula.iam.v1.RoleOrBuilder> 
      getRolesOrBuilderList() {
    return roles_;
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  @java.lang.Override
  public int getRolesCount() {
    return roles_.size();
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  @java.lang.Override
  public com.saltoapis.nebula.iam.v1.Role getRoles(int index) {
    return roles_.get(index);
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  public com.saltoapis.nebula.iam.v1.RoleOrBuilder getRolesOrBuilder(
      int index) {
    return roles_.get(index);
  }
  private void ensureRolesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.saltoapis.nebula.iam.v1.Role> tmp = roles_;
    if (!tmp.isModifiable()) {
      roles_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  private void setRoles(
      int index, com.saltoapis.nebula.iam.v1.Role value) {
    value.getClass();
  ensureRolesIsMutable();
    roles_.set(index, value);
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  private void addRoles(com.saltoapis.nebula.iam.v1.Role value) {
    value.getClass();
  ensureRolesIsMutable();
    roles_.add(value);
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  private void addRoles(
      int index, com.saltoapis.nebula.iam.v1.Role value) {
    value.getClass();
  ensureRolesIsMutable();
    roles_.add(index, value);
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  private void addAllRoles(
      java.lang.Iterable<? extends com.saltoapis.nebula.iam.v1.Role> values) {
    ensureRolesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, roles_);
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  private void clearRoles() {
    roles_ = emptyProtobufList();
  }
  /**
   * <pre>
   * The field name should match the noun `roles` in the method name. There
   * will be a maximum number of items returned based on the `page_size` field
   * in the request.
   * </pre>
   *
   * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
   */
  private void removeRoles(int index) {
    ensureRolesIsMutable();
    roles_.remove(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  private java.lang.String nextPageToken_;
  /**
   * <pre>
   * Token to retrieve the next page of results, or empty if there are no more
   * results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  @java.lang.Override
  public java.lang.String getNextPageToken() {
    return nextPageToken_;
  }
  /**
   * <pre>
   * Token to retrieve the next page of results, or empty if there are no more
   * results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nextPageToken_);
  }
  /**
   * <pre>
   * Token to retrieve the next page of results, or empty if there are no more
   * results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @param value The nextPageToken to set.
   */
  private void setNextPageToken(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nextPageToken_ = value;
  }
  /**
   * <pre>
   * Token to retrieve the next page of results, or empty if there are no more
   * results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  private void clearNextPageToken() {

    nextPageToken_ = getDefaultInstance().getNextPageToken();
  }
  /**
   * <pre>
   * Token to retrieve the next page of results, or empty if there are no more
   * results in the list.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @param value The bytes for nextPageToken to set.
   */
  private void setNextPageTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nextPageToken_ = value.toStringUtf8();

  }

  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.saltoapis.nebula.iam.v1.ListRolesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.saltoapis.nebula.iam.v1.ListRolesResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * The response message for [`ListRoles`][salto.nebula.iam.v1.IAMService.ListRoles]
   * </pre>
   *
   * Protobuf type {@code salto.nebula.iam.v1.ListRolesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.saltoapis.nebula.iam.v1.ListRolesResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:salto.nebula.iam.v1.ListRolesResponse)
      com.saltoapis.nebula.iam.v1.ListRolesResponseOrBuilder {
    // Construct using com.saltoapis.nebula.iam.v1.ListRolesResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.saltoapis.nebula.iam.v1.Role> getRolesList() {
      return java.util.Collections.unmodifiableList(
          instance.getRolesList());
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    @java.lang.Override
    public int getRolesCount() {
      return instance.getRolesCount();
    }/**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    @java.lang.Override
    public com.saltoapis.nebula.iam.v1.Role getRoles(int index) {
      return instance.getRoles(index);
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder setRoles(
        int index, com.saltoapis.nebula.iam.v1.Role value) {
      copyOnWrite();
      instance.setRoles(index, value);
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder setRoles(
        int index, com.saltoapis.nebula.iam.v1.Role.Builder builderForValue) {
      copyOnWrite();
      instance.setRoles(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder addRoles(com.saltoapis.nebula.iam.v1.Role value) {
      copyOnWrite();
      instance.addRoles(value);
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder addRoles(
        int index, com.saltoapis.nebula.iam.v1.Role value) {
      copyOnWrite();
      instance.addRoles(index, value);
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder addRoles(
        com.saltoapis.nebula.iam.v1.Role.Builder builderForValue) {
      copyOnWrite();
      instance.addRoles(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder addRoles(
        int index, com.saltoapis.nebula.iam.v1.Role.Builder builderForValue) {
      copyOnWrite();
      instance.addRoles(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder addAllRoles(
        java.lang.Iterable<? extends com.saltoapis.nebula.iam.v1.Role> values) {
      copyOnWrite();
      instance.addAllRoles(values);
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder clearRoles() {
      copyOnWrite();
      instance.clearRoles();
      return this;
    }
    /**
     * <pre>
     * The field name should match the noun `roles` in the method name. There
     * will be a maximum number of items returned based on the `page_size` field
     * in the request.
     * </pre>
     *
     * <code>repeated .salto.nebula.iam.v1.Role roles = 1;</code>
     */
    public Builder removeRoles(int index) {
      copyOnWrite();
      instance.removeRoles(index);
      return this;
    }

    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return The nextPageToken.
     */
    @java.lang.Override
    public java.lang.String getNextPageToken() {
      return instance.getNextPageToken();
    }
    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return The bytes for nextPageToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      return instance.getNextPageTokenBytes();
    }
    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @param value The nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      copyOnWrite();
      instance.setNextPageToken(value);
      return this;
    }
    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPageToken() {
      copyOnWrite();
      instance.clearNextPageToken();
      return this;
    }
    /**
     * <pre>
     * Token to retrieve the next page of results, or empty if there are no more
     * results in the list.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     * @param value The bytes for nextPageToken to set.
     * @return This builder for chaining.
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNextPageTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:salto.nebula.iam.v1.ListRolesResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.saltoapis.nebula.iam.v1.ListRolesResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "roles_",
            com.saltoapis.nebula.iam.v1.Role.class,
            "nextPageToken_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.saltoapis.nebula.iam.v1.ListRolesResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.saltoapis.nebula.iam.v1.ListRolesResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.saltoapis.nebula.iam.v1.ListRolesResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:salto.nebula.iam.v1.ListRolesResponse)
  private static final com.saltoapis.nebula.iam.v1.ListRolesResponse DEFAULT_INSTANCE;
  static {
    ListRolesResponse defaultInstance = new ListRolesResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListRolesResponse.class, defaultInstance);
  }

  public static com.saltoapis.nebula.iam.v1.ListRolesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListRolesResponse> PARSER;

  public static com.google.protobuf.Parser<ListRolesResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

