// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/nebula/unit/v1/unit.proto
// Protobuf Java Version: 4.29.2

package com.saltoapis.nebula.unit.v1;

public interface UpdateUnitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.nebula.unit.v1.UpdateUnitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The unit resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.unit.v1.Unit unit = 1;</code>
   * @return Whether the unit field is set.
   */
  boolean hasUnit();
  /**
   * <pre>
   * The unit resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.unit.v1.Unit unit = 1;</code>
   * @return The unit.
   */
  com.saltoapis.nebula.unit.v1.Unit getUnit();
  /**
   * <pre>
   * The unit resource which replaces the resource on the server.
   * </pre>
   *
   * <code>.salto.nebula.unit.v1.Unit unit = 1;</code>
   */
  com.saltoapis.nebula.unit.v1.UnitOrBuilder getUnitOrBuilder();

  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();
  /**
   * <pre>
   * The update mask applied to the resource.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2;</code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
