// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salto/longrunning/v1/operation.proto
// Protobuf Java Version: 4.33.1

package com.saltoapis.longrunning.v1;

@com.google.protobuf.Generated
public interface ListOperationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:salto.longrunning.v1.ListOperationsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The maximum number of items to return.
   * </pre>
   *
   * <code>int32 page_size = 1;</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <pre>
   * The `next_page_token` value returned from a previous `List` request, if
   * any.
   * </pre>
   *
   * <code>string page_token = 2;</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <pre>
   * The `next_page_token` value returned from a previous `List` request, if
   * any.
   * </pre>
   *
   * <code>string page_token = 2;</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <pre>
   * A filter that chooses which operations to return. The maximum
   * length of the filter is 20000 characters.
   * </pre>
   *
   * <code>string filter = 3;</code>
   * @return The filter.
   */
  java.lang.String getFilter();
  /**
   * <pre>
   * A filter that chooses which operations to return. The maximum
   * length of the filter is 20000 characters.
   * </pre>
   *
   * <code>string filter = 3;</code>
   * @return The bytes for filter.
   */
  com.google.protobuf.ByteString
      getFilterBytes();
}
